/**
 * Author: sascha_lammers@gmx.de
 */

#pragma once

// Shared LVGL graphics helpers: theme colors, fonts, page scaffolding (top bar with the
// clock, title, optional info text), cards, labels, value rows, weather/moon icons and
// text fitting.
//
// The widget style lives here so that every application screen (for example the weather
// station plugin) looks the same. Screens are built by application plugins and are shown
// by LVGLScreenManager, see lvgl_screen.h.

#include <Arduino_compat.h>

#if IOT_LVGL_SUPPORT

#include <lvgl.h>

namespace LVGLUI {

// ------------------------------------------------------------------------------------------
// theme
// ------------------------------------------------------------------------------------------
static constexpr uint32_t kColorBackground = 0x0b0f14;
static constexpr uint32_t kColorBar = 0x12181f;
static constexpr uint32_t kColorCard = 0x182029;
static constexpr uint32_t kColorCardAlt = 0x161d25;
static constexpr uint32_t kColorBorder = 0x2b3844;
static constexpr uint32_t kColorText = 0xffffff;
static constexpr uint32_t kColorTextValue = 0xc8d4dd;
static constexpr uint32_t kColorTextLabel = 0x7fa8c9;
static constexpr uint32_t kColorTextMuted = 0x4d6274;
static constexpr uint32_t kColorAccent = 0x00ffff;
static constexpr uint32_t kColorHighlight = 0xffff00;
// active/on state: the fill of an active tile or button, the indicator of an arc, the level fill of a
// dimmer and the bars of a climate tile
static constexpr uint32_t kColorActive = 0xff8000;
// notes, status lines and error messages. They are not a state of a widget, they tell the user why a
// screen has no content (same orange as kColorActive, a different meaning)
static constexpr uint32_t kColorAlert = 0xff8000;
static constexpr uint32_t kColorError = 0xff0000;

// height of the top bar and the footer strip
static constexpr lv_coord_t kBarHeight = 36;
static constexpr lv_coord_t kFooterHeight = 46;
// distance between the screen edge and the content
static constexpr lv_coord_t kPagePad = 8;
// radius of cards and icons
static constexpr lv_coord_t kCardRadius = 12;

// ------------------------------------------------------------------------------------------
// fonts
// ------------------------------------------------------------------------------------------
// fonts enabled in lv_conf.h (LV_FONT_MONTSERRAT_*)
extern const lv_font_t *const kFontSmall;  // 12
extern const lv_font_t *const kFontNormal;  // 14
extern const lv_font_t *const kFontMedium;  // 16
extern const lv_font_t *const kFontLarge;  // 20
extern const lv_font_t *const kFontTitle;  // 24
extern const lv_font_t *const kFontValue;  // 28
extern const lv_font_t *const kFontHuge;  // 32

// all fonts from large to small, used by fitText()
extern const lv_font_t *const kFontLadder[];
extern const uint8_t kFontLadderSize;

// ------------------------------------------------------------------------------------------
// Material Design Icons. The fonts are generated by scripts/tools/fonts/generate_lvgl_fonts.py
// (only the glyphs the screens use, include/lvgl_mdi_icons.h holds the literals). LVGL cannot
// scale a font, so every size is a font of its own and only these two exist - the layouts use
// kIconSizeSmall for inline glyphs and kIconSizeLarge for everything tile sized
// ------------------------------------------------------------------------------------------
extern "C" {
    extern const lv_font_t lv_font_mdi_20;
    extern const lv_font_t lv_font_mdi_48;
}

static constexpr lv_coord_t kIconSizeSmall = 20;
static constexpr lv_coord_t kIconSizeLarge = 48;

// color argument of createIcon()/setIcon(): the theme color of that icon (LVGLUI::kIconColor)
static constexpr uint32_t kIconColorDefault = 0;

// ------------------------------------------------------------------------------------------
// text
// ------------------------------------------------------------------------------------------
// measures the width of a single line of text
lv_coord_t getTextWidth(const char *text, const lv_font_t *font);

// sets the text and shrinks the font until it fits into maxWidth. If no font fits the text is
// cut off with an ellipsis. Returns true if the text fits without being cut off
bool fitText(lv_obj_t *label, const char *text, lv_coord_t maxWidth);

// same as fitText() but the font of the label is never increased - it is the maximum. Use it
// for text with a size of its own (labels of a fixed layout, keys of a key/value list), fitText()
// picks the largest font that fits, which turns short text into very large text.
// allowScroll keeps the smallest font and scrolls the text slowly instead of cutting it off with
// an ellipsis. Use it for the few values that can be arbitrarily long (host names, SSIDs).
// maxWidth 0 uses the width that was set with lv_obj_set_width()
bool fitTextDown(lv_obj_t *label, const char *text, lv_coord_t maxWidth = 0, bool allowScroll = false);

// same as fitText() but scrolls the text slowly (circular) if it does not fit in any font.
// Use it for the few strings that can be arbitrarily long (descriptions, hostnames), not for
// short values - scrolling text is hard to read and should stay the exception
bool fitTextOrScroll(lv_obj_t *label, const char *text, lv_coord_t maxWidth);

// sets the text without measuring, with a fixed font and color
void setText(lv_obj_t *label, const char *text, const lv_font_t *font = nullptr, uint32_t color = kColorText);

// Places two labels of one row next to each other in the middle of a row of `width` pixels
// ("name" on the left, "date" on the right, separated by `gap`). The y of the name label is the
// top of the row, the date is put on the same baseline. Both fonts are their maximum, they
// shrink together until the pair fits and are cut off if even the smallest font is too large.
// Used by the moon phase rows
void layoutCenteredPair(lv_obj_t *name, lv_obj_t *date, const char *nameText, const char *dateText,
                        lv_coord_t width, lv_coord_t gap);

// ------------------------------------------------------------------------------------------
// widgets
// ------------------------------------------------------------------------------------------
// handles of the page created by createPage()
struct PageRefs {
    lv_obj_t *root{nullptr};
    lv_obj_t *date{nullptr};
    lv_obj_t *time{nullptr};
    lv_obj_t *zone{nullptr};
    lv_obj_t *title{nullptr};
    lv_obj_t *info{nullptr};

    // true if the page has been created
    bool isValid() const {
        return root != nullptr;
    }
};

// creates the page background and the top bar: the title (and the optional info text) on the
// left, the date, the time and the time zone right aligned. The content area starts below the
// bar (LVGLUI::kBarHeight) and ends above the footer (height - kFooterHeight). A tap in the bar
// is handled by the screen manager, it always opens the screen overview
PageRefs createPage(lv_obj_t *parent, const char *title, const char *right = nullptr);

// refreshes date/time/timezone of the top bar from the local time
void setClock(const PageRefs &page, bool format24h);

// formats the current local time, empty strings if the clock is not set yet
void formatClock(bool format24h, String &date, String &time, String &zone);

// creates a footer strip and returns it as the parent for footer content
lv_obj_t *createFooter(lv_obj_t *parent);

// Plain transparent container without background, border, radius or padding, not scrollable.
// Use it as the parent of content that is rebuilt while the page around it stays: clear it with
// lv_obj_clean() and build the new content below it. The position is relative to parent, like
// every other widget created by these helpers
lv_obj_t *createContainer(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h);

// card with optional title in the upper left corner, content can be added as a child
lv_obj_t *createCard(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h,
                     const char *title = nullptr);

// label at an absolute position, width is set to maxWidth if it is not LV_SIZE_CONTENT
lv_obj_t *addLabel(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, const char *text,
                   const lv_font_t *font, uint32_t color, lv_coord_t maxWidth = LV_SIZE_CONTENT,
                   lv_text_align_t align = LV_TEXT_ALIGN_LEFT);

// 1 px separator line
lv_obj_t *addSeparator(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w);

// "label" on the left and "value" on the right, used by key/value lists
struct KeyValueRefs {
    lv_obj_t *key{nullptr};
    lv_obj_t *value{nullptr};
};

// adds one key/value row, both labels fit their part of the width (the value shrinks first).
// keyWidth 0 gives the key 45% of the row, a fixed width is used to lay several rows out with
// one value column (the key then takes only the space its longest entry needs)
KeyValueRefs addKeyValue(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t gap,
                         const char *key, const char *value, lv_coord_t keyWidth = 0);

// ------------------------------------------------------------------------------------------
// tiles, arcs and buttons of an application dashboard
// ------------------------------------------------------------------------------------------
// state of a tile, drawn with the border and the background of setTileState()
enum class TileState : uint8_t {
    OFF,          // inactive
    ON,           // active/on
    PENDING,      // an action was sent and is not confirmed yet
    UNAVAILABLE,  // no value or the entity is not available
};

// card that fills the cells of a tile, the content is added as a child. The state is drawn with
// setTileState(). filled = false keeps the card background and only colors the border, for tiles
// that show their state with a fill or with bars (a dimmer or a climate tile)
lv_obj_t *createTile(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h);
void setTileState(lv_obj_t *tile, TileState state, bool filled = true);

// Image of a tile (the camera preview of a picture tile). The pixels belong to the caller: it
// keeps a lv_img_dsc_t with LV_IMG_CF_TRUE_COLOR (RGB565, where red/blue depend on
// LV_COLOR_16_SWAP) and sets it with lv_img_set_src(image, &descriptor). The image is created
// without a source, which has to be exactly w x h pixels
lv_obj_t *createImage(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h);

// arc of a dashboard tile: 270 degrees with the gap centered at the bottom, value range 0..100.
// The arc can be dragged by the user, the value is read with lv_arc_get_value()
static constexpr uint16_t kArcRotation = 135;
// thickness of the ring (the track and the indicator). LVGL has no knob size of its own, it draws
// the knob as a circle of arc_width + 2 x pad (LV_PART_KNOB), see createArc()
static constexpr lv_coord_t kArcWidth = 18;
// `ringWidth` is the thickness of the ring (the track and the indicator), the knob follows it
lv_obj_t *createArc(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t size, lv_coord_t ringWidth = kArcWidth);
// sets the value and the color of the indicator, the knob stays white like on the Home Assistant
// thermostat card
void setArcValue(lv_obj_t *arc, int16_t value, uint32_t color = kColorAccent);

// small button with a centered label (the label is the first child of the object). An empty text
// creates a button without a label, use createIconButton() for one with an icon inside
lv_obj_t *createButton(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h,
                       const char *text, const lv_font_t *font = nullptr);

// active buttons are filled with the accent color, inactive ones are plain cards. A label of the
// button (if it has one) switches to a dark text color while it is active
void setButtonActive(lv_obj_t *button, bool active);

// Level fill of a dimmer tile or of a panel slider: a rounded bar that grows from the bottom of a
// track (x, y, w, trackHeight). The track itself stays empty, the fill is the visible level
// level fill of a dashboard tile (the level of a dimmer that is dragged): the height follows the
// level, so only the edge that moves is seen as a shape of its own - the other end is clipped by the
// rounded tile (see createLevelFill()). The edge that moves is nearly square
static constexpr lv_coord_t kLevelFillRadius = 5;
lv_obj_t *createLevelFill(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h);
void setLevelFill(lv_obj_t *fill, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t trackHeight,
                  uint8_t percent, uint32_t color = kColorActive);

// Scrollable list of the panels (option and effect list): a card with a scrollbar on the right,
// the items are added by the caller with addListItem() and placed in their own coordinates
lv_obj_t *createList(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h);
// one item of a list, a card with a centered label
lv_obj_t *addListItem(lv_obj_t *list, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h, const char *text);
// the item that is set is filled like an active tile, the label stays white
void setListItemActive(lv_obj_t *item, bool active);

// removes LV_OBJ_FLAG_CLICKABLE from the object and all children, so that a click reaches the
// tile below it (every object created with lv_obj_create() is clickable by default)
void clearClickable(lv_obj_t *obj);

// ------------------------------------------------------------------------------------------
// icons (drawn with LVGL primitives, no image assets - they can be replaced by lv_img later)
// ------------------------------------------------------------------------------------------
enum class IconType : uint8_t {
    SUN,
    PARTLY_CLOUDY,
    CLOUDY,
    RAIN,
    SNOW,
    STORM,
    FOG,
    UNKNOWN,
    // icons of the screen overview, see LVGLScreen::getIcon(). Adding entries at the end keeps
    // the weather icons above stable, they are used by the condition mapping of the screens
    HOUSE,
    CALENDAR,
    MOON,
    INFO,
    CLOCK,
    GLOBE,
    POWER,
    PICTURE,
    // status icons of the application dashboards (tiles of the home assistant screen), appended
    // so that the values of the icons above stay stable
    BULB,
    PLUG,
    TOGGLE,
    THERMOMETER,
    HUMIDITY,
    BUTTON,
    DIMMER,
    RADIATOR,
    FAN,
    // state glyphs of the climate mode bar (appended, the values above stay stable)
    POWER_SYMBOL,
    FLAME,
    SNOWFLAKE,
    // status icons of a motion sensor tile (appended, the values above stay stable)
    MOTION,
    // folder, used by the area tile of the home assistant dashboard
    AREA,
    // arrow pointing to the left, used by the back tile of an area page
    BACK,
    // glyphs of the home assistant panels (appended, the values above stay stable)
    PALETTE,
    EFFECT,
    RECORD,
    PLUS,
    MINUS,
    // state glyphs of a switch (the handle shows the state) and the buttons of the light panel
    // (appended, the values above stay stable)
    TOGGLE_OFF,
    BRIGHTNESS,
    COLOR_TEMP,
    // CO2 molecule, used by a sensor tile of an air quality sensor (appended, see
    // `scripts/tools/fonts/generate_lvgl_fonts.py`)
    CO2,
    LOCK,
    // tile icons of a general purpose dashboard (appended, one per `icon:` name of the
    // configuration, the MDI name is the value of the key)
    GAUGE,
    CAMERA,
    REMOTE,
    LIGHTBULB_OFF,
    LIGHTBULB_ON,
    FLASH_OFF,
    HOME,
    HOME_ASSISTANT,
    // WiFi state in the header of the home assistant quick settings (appended, one glyph per
    // state: associated, connecting, an error and the interface switched off)
    WIFI,
    WIFI_REMOVE,
    WIFI_ALERT,
    WIFI_OFF,
    // state and device_class glyphs of the home assistant tiles (appended, the values above stay
    // stable): the off state of an icon and the glyphs the `device_class` of an entity maps to
    POWER_PLUG_OFF,
    MOTION_SENSOR_OFF,
    SINE_WAVE,
    CURRENT_AC,
    LIGHTNING_BOLT,
};

// creates an icon container with the icon inside, size x size pixels at x,y. Use kIconSizeSmall or
// kIconSizeLarge, the glyph is centered in the container. color 0 uses the theme color of the icon
lv_obj_t *createIcon(lv_obj_t *parent, IconType type, lv_coord_t x, lv_coord_t y, lv_coord_t size,
                     uint32_t color = kIconColorDefault);

// redraws an icon container created by createIcon()
void setIcon(lv_obj_t *icon, IconType type, lv_coord_t size, uint32_t color = kIconColorDefault);

// true when the container already draws the glyph of `type`. setIcon() rebuilds the label, so a
// caller that redraws an icon on every update skips it while the glyph does not change
bool isIcon(lv_obj_t *icon, IconType type);

// recolors the glyph of an icon, a filled (active) tile or button draws its icons white
void setIconColor(lv_obj_t *icon, uint32_t color);

// button with an icon in the middle and no label, used by the climate mode bar
lv_obj_t *createIconButton(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h,
                           IconType type, lv_coord_t iconSize);

// house icon used by the indoor screen
lv_obj_t *createHouseIcon(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t size);

// Circular arrow of the rotate setting: a 300 degree arc with the gap on the right and the head of
// the arrow beside it (also drawn with lv_arc, the MDI subset fonts have no glyph for it)
lv_obj_t *createRotateIcon(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t size, uint32_t color = kColorTextValue);

// moon disc: a light circle with a dark circle clipped to it. The shadow is moved by
// setMoonPhase(), illumination 0 = new moon, 0.5 = half, 1 = full
lv_obj_t *createMoon(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t size);
void setMoonPhase(lv_obj_t *moon, float illumination, bool waxing);

} // namespace LVGLUI

#endif
