/**
 * Author: sascha_lammers@gmx.de
 */

#include "lvgl_ui.h"
// generated Material Design Icons, see scripts/tools/fonts/generate_lvgl_fonts.py
#include "lvgl_mdi_icons.h"

#if IOT_LVGL_SUPPORT

#include <lvgl.h>
#include <time.h>

namespace LVGLUI {

const lv_font_t *const kFontSmall = &lv_font_montserrat_12;
const lv_font_t *const kFontNormal = &lv_font_montserrat_14;
const lv_font_t *const kFontMedium = &lv_font_montserrat_16;
const lv_font_t *const kFontLarge = &lv_font_montserrat_20;
const lv_font_t *const kFontTitle = &lv_font_montserrat_24;
const lv_font_t *const kFontValue = &lv_font_montserrat_28;
const lv_font_t *const kFontHuge = &lv_font_montserrat_32;

const lv_font_t *const kFontLadder[] = {
    kFontHuge, kFontValue, kFontTitle, kFontLarge, kFontMedium, kFontNormal, kFontSmall,
};
const uint8_t kFontLadderSize = static_cast<uint8_t>(sizeof(kFontLadder) / sizeof(kFontLadder[0]));

// ------------------------------------------------------------------------------------------
// helpers
// ------------------------------------------------------------------------------------------
static lv_obj_t *_container(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h)
{
    auto obj = lv_obj_create(parent);
    lv_obj_set_pos(obj, x, y);
    if (w != LV_SIZE_CONTENT && h != LV_SIZE_CONTENT) {
        lv_obj_set_size(obj, w, h);
    }
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN);
    lv_obj_set_style_radius(obj, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN);
    return obj;
}

static lv_obj_t *_disc(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t d, uint32_t color,
                       lv_opa_t opa = LV_OPA_COVER)
{
    auto obj = _container(parent, x, y, d, d);
    lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, LV_PART_MAIN);
    lv_obj_set_style_bg_color(obj, lv_color_hex(color), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(obj, opa, LV_PART_MAIN);
    return obj;
}

// ------------------------------------------------------------------------------------------
// Material Design Icons (MDI)
//
// The icons are glyphs of the subset fonts in src/plugins/lvgl/fonts/, generated by
// scripts/tools/fonts/generate_lvgl_fonts.py (the literals come from include/lvgl_mdi_icons.h).
// Both tables are indexed with IconType, so their order is the order of the enum; the generator
// verifies it (--check).
// ------------------------------------------------------------------------------------------

// glyph of every icon, in the order of IconType
static const char *const kIconGlyph[] = {
    LVGL_MDI_SUN, LVGL_MDI_PARTLY_CLOUDY, LVGL_MDI_CLOUDY, LVGL_MDI_RAIN,
    LVGL_MDI_SNOW, LVGL_MDI_STORM, LVGL_MDI_FOG, LVGL_MDI_UNKNOWN,
    LVGL_MDI_HOUSE, LVGL_MDI_CALENDAR, LVGL_MDI_MOON, LVGL_MDI_INFO,
    LVGL_MDI_CLOCK, LVGL_MDI_GLOBE, LVGL_MDI_POWER, LVGL_MDI_PICTURE,
    LVGL_MDI_BULB, LVGL_MDI_PLUG, LVGL_MDI_TOGGLE, LVGL_MDI_THERMOMETER,
    LVGL_MDI_HUMIDITY, LVGL_MDI_BUTTON, LVGL_MDI_DIMMER, LVGL_MDI_RADIATOR,
    LVGL_MDI_FAN, LVGL_MDI_POWER_SYMBOL, LVGL_MDI_FLAME, LVGL_MDI_SNOWFLAKE,
    LVGL_MDI_MOTION, LVGL_MDI_AREA, LVGL_MDI_BACK, LVGL_MDI_PALETTE,
    LVGL_MDI_EFFECT, LVGL_MDI_RECORD, LVGL_MDI_PLUS, LVGL_MDI_MINUS,
    LVGL_MDI_TOGGLE_OFF, LVGL_MDI_BRIGHTNESS, LVGL_MDI_COLOR_TEMP, LVGL_MDI_CO2,
    LVGL_MDI_LOCK, LVGL_MDI_GAUGE, LVGL_MDI_CAMERA, LVGL_MDI_REMOTE,
    LVGL_MDI_LIGHTBULB_OFF, LVGL_MDI_LIGHTBULB_ON, LVGL_MDI_FLASH_OFF, LVGL_MDI_HOME,
    LVGL_MDI_HOME_ASSISTANT,
    LVGL_MDI_WIFI, LVGL_MDI_WIFI_REMOVE, LVGL_MDI_WIFI_ALERT, LVGL_MDI_WIFI_OFF,
    LVGL_MDI_POWER_PLUG_OFF, LVGL_MDI_MOTION_SENSOR_OFF, LVGL_MDI_SINE_WAVE,
    LVGL_MDI_CURRENT_AC, LVGL_MDI_LIGHTNING_BOLT,
    LVGL_MDI_AUTORENEW, LVGL_MDI_WATER,
    LVGL_MDI_FAN_AUTO, LVGL_MDI_WINDY, LVGL_MDI_POWER_OFF,
};

// theme color of every icon, in the same order. A filled tile or button redraws them white with
// setIconColor()
static const uint32_t kIconColor[] = {
    kColorHighlight, kColorHighlight, kColorTextValue, kColorAccent,
    kColorAccent, kColorHighlight, kColorTextValue, kColorTextMuted,
    kColorTextValue, kColorTextValue, kColorText, kColorAccent,
    kColorTextValue, kColorAccent, kColorActive, kColorTextValue,
    kColorHighlight, kColorTextValue, kColorTextValue, kColorActive,
    kColorAccent, kColorTextValue, kColorHighlight, kColorActive,
    kColorAccent, kColorTextValue, kColorTextValue, kColorTextValue,
    kColorHighlight, kColorAccent, kColorTextValue, kColorAccent,
    kColorHighlight, kColorTextValue, kColorTextValue, kColorTextValue,
    kColorTextValue, kColorTextValue, kColorTextValue,
    kColorAccent, kColorTextValue, kColorActive, kColorTextValue,
    kColorTextValue, kColorTextValue, kColorHighlight, kColorTextValue,
    kColorTextValue, kColorAccent,
    kColorTextValue, kColorTextMuted, kColorError, kColorTextMuted,
    kColorTextValue, kColorTextValue, kColorAccent, kColorAccent, kColorHighlight,
    kColorTextValue, kColorAccent,
    kColorTextValue, kColorTextValue, kColorTextValue,
};

static constexpr uint8_t kIconCount = static_cast<uint8_t>(sizeof(kIconGlyph) / sizeof(kIconGlyph[0]));

// font an icon is drawn with. There are two sizes only, everything else is rounded to them
static const lv_font_t *_iconFont(lv_coord_t size)
{
    return (size <= kIconSizeSmall) ? &lv_font_mdi_20 : &lv_font_mdi_48;
}


// light disc with a dark disc clipped to it (a circle), the shadow is moved by setMoonPhase()
static lv_obj_t *_moon(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t size)
{
    auto moon = _disc(parent, x, y, size, kColorText);
    lv_obj_set_style_clip_corner(moon, true, LV_PART_MAIN);
    _disc(moon, 0, 0, size, kColorCard);
    return moon;
}


static void _drawIcon(lv_obj_t *parent, IconType type, lv_coord_t size, uint32_t color = kIconColorDefault)
{
    const auto index = static_cast<uint8_t>(type);
    if (index >= kIconCount) {
        return;
    }
    auto label = lv_label_create(parent);
    // the glyph font has to be set before the text: the label lays the text out with the font of
    // its style as soon as the text is set
    lv_obj_set_style_text_font(label, _iconFont(size), LV_PART_MAIN);
    lv_obj_set_style_text_color(label, lv_color_hex(color ? color : kIconColor[index]), LV_PART_MAIN);
    lv_obj_set_style_pad_all(label, 0, LV_PART_MAIN);
    lv_label_set_text(label, kIconGlyph[index]);
    lv_obj_center(label);
}

// ------------------------------------------------------------------------------------------
// text
// ------------------------------------------------------------------------------------------
lv_coord_t getTextWidth(const char *text, const lv_font_t *font)
{
    if (!text || !font) {
        return 0;
    }
    lv_point_t size;
    lv_txt_get_size(&size, text, font, 0, 0, LV_COORD_MAX, LV_TEXT_FLAG_NONE);
    return size.x;
}

// width a label was given with lv_obj_set_width(), 0 when it uses the content size
static lv_coord_t _explicitWidth(lv_obj_t *label)
{
    if (label == nullptr) {
        return 0;
    }
    const auto width = lv_obj_get_style_width(label, LV_PART_MAIN);
    return (width > 0 && !LV_COORD_IS_SPEC(width)) ? width : 0;
}

// usable width for a label: the value the caller passed, or the width set with
// lv_obj_set_width() when it cannot be used yet. 0 means "no width known"
static lv_coord_t _usableWidth(lv_obj_t *label, lv_coord_t width)
{
    // The screens pass lv_obj_get_width() of the label. That is the size of the last layout
    // pass and still 0 while the widget tree was not laid out - the screens create and fill
    // their widgets in the same tick (the screen is shown), so using it would set the width of
    // the label to 0 and the text could never be displayed. The width that was set with
    // lv_obj_set_width() is the one lv_obj_get_width() returns after the next layout pass
    if (width > 0 && !LV_COORD_IS_SPEC(width)) {
        return width;
    }
    return _explicitWidth(label);
}

// index of a font inside kFontLadder (sorted from large to small). A font that is not part of
// the ladder gets the first entry that is not larger than it
static uint8_t _ladderIndex(const lv_font_t *font)
{
    for (uint8_t i = 0; i < kFontLadderSize; i++) {
        if (kFontLadder[i] == font) {
            return i;
        }
    }
    for (uint8_t i = 0; i < kFontLadderSize; i++) {
        if (kFontLadder[i]->line_height <= font->line_height) {
            return i;
        }
    }
    return static_cast<uint8_t>(kFontLadderSize - 1);
}

// distance of the baseline from the top of the line (the same calculation lv_draw_label uses)
static lv_coord_t _baseline(const lv_font_t *font)
{
    return static_cast<lv_coord_t>(font->line_height - font->base_line - font->underline_position);
}

// sets the text of a label, the size and the long mode. The largest font that may be used is
// the one the label was created with unless allowGrow is set (fitText picks the largest font
// that fits, fitTextDown only shrinks). If no font fits the text is cut off with an ellipsis or
// it scrolls slowly
static lv_obj_t *_applyText(lv_obj_t *label, const char *text, lv_coord_t maxWidth, bool allowScroll,
                            bool allowGrow, bool &fits)
{
    fits = false;
    if (!label) {
        return label;
    }
    text = text ? text : "";
    maxWidth = _usableWidth(label, maxWidth);
    if (maxWidth > 0) {
        lv_obj_set_width(label, maxWidth);
    }
    else {
        // no width known (the label was not resized and has no explicit width): only measure,
        // do not resize the label
        maxWidth = LV_COORD_MAX;
    }
    const uint8_t start = allowGrow ? 0 : _ladderIndex(lv_obj_get_style_text_font(label, LV_PART_MAIN));
    for (uint8_t i = start; i < kFontLadderSize; i++) {
        auto font = kFontLadder[i];
        if (getTextWidth(text, font) <= maxWidth) {
            lv_obj_set_style_text_font(label, font, LV_PART_MAIN);
            lv_label_set_long_mode(label, LV_LABEL_LONG_DOT);
            lv_label_set_text(label, text);
            fits = true;
            return label;
        }
    }
    // no font fits: smallest font, ellipsis or a slow circular scroll
    lv_obj_set_style_text_font(label, kFontSmall, LV_PART_MAIN);
    if (allowScroll) {
        lv_label_set_long_mode(label, LV_LABEL_LONG_SCROLL_CIRCULAR);
        // scroll speed is a style property in LVGL 8.3+, 25 px/s is slow on purpose
        lv_obj_set_style_anim_speed(label, 25, LV_PART_MAIN);
    }
    else {
        lv_label_set_long_mode(label, LV_LABEL_LONG_DOT);
    }
    lv_label_set_text(label, text);
    return label;
}

// shrinks the font until the text fits, the current font is never increased. Used for labels
// with a size of its own (labels of a fixed layout, keys of a key/value list): fitText() picks
// the largest font that fits, which would turn short text into very large text
bool fitTextDown(lv_obj_t *label, const char *text, lv_coord_t maxWidth, bool allowScroll)
{
    bool fits;
    _applyText(label, text, maxWidth, allowScroll, false, fits);
    return fits;
}

bool fitText(lv_obj_t *label, const char *text, lv_coord_t maxWidth)
{
    bool fits;
    _applyText(label, text, maxWidth, false, true, fits);
    return fits;
}

bool fitTextOrScroll(lv_obj_t *label, const char *text, lv_coord_t maxWidth)
{
    bool fits;
    _applyText(label, text, maxWidth, true, true, fits);
    return fits;
}

void layoutCenteredPair(lv_obj_t *name, lv_obj_t *date, const char *nameText, const char *dateText,
                        lv_coord_t width, lv_coord_t gap)
{
    if (!name || !date || width <= 0) {
        return;
    }
    nameText = nameText ? nameText : "";
    dateText = dateText ? dateText : "";
    if (gap < 0) {
        gap = 0;
    }

    // the font a label was created with is the largest one it may use, both shrink together
    // until the pair fits (the larger one is shrunk first)
    uint8_t nameIndex = _ladderIndex(lv_obj_get_style_text_font(name, LV_PART_MAIN));
    uint8_t dateIndex = _ladderIndex(lv_obj_get_style_text_font(date, LV_PART_MAIN));
    lv_coord_t nameWidth = 0;
    lv_coord_t dateWidth = 0;
    for (uint8_t i = 0; i < (kFontLadderSize * 2); i++) {
        nameWidth = getTextWidth(nameText, kFontLadder[nameIndex]);
        dateWidth = getTextWidth(dateText, kFontLadder[dateIndex]);
        if ((nameWidth + gap + dateWidth) <= width) {
            break;
        }
        if (nameIndex == dateIndex) {
            if ((nameIndex + 1) >= kFontLadderSize) {
                break;
            }
            nameIndex++;
            dateIndex++;
        }
        else if (nameIndex < dateIndex) {
            nameIndex++; // the name uses the larger font
        }
        else {
            dateIndex++; // the date uses the larger font
        }
    }
    if ((nameWidth + gap + dateWidth) > width) {
        // even the smallest font is too large, both get half of the row and are cut off
        nameWidth = static_cast<lv_coord_t>((width - gap) / 2);
        dateWidth = static_cast<lv_coord_t>(width - gap - nameWidth);
    }

    const auto nameFont = kFontLadder[nameIndex];
    const auto dateFont = kFontLadder[dateIndex];
    lv_obj_set_style_text_font(name, nameFont, LV_PART_MAIN);
    lv_obj_set_style_text_font(date, dateFont, LV_PART_MAIN);
    lv_label_set_long_mode(name, LV_LABEL_LONG_DOT);
    lv_label_set_long_mode(date, LV_LABEL_LONG_DOT);
    lv_obj_set_size(name, nameWidth, lv_font_get_line_height(nameFont));
    lv_obj_set_size(date, dateWidth, lv_font_get_line_height(dateFont));

    // the name keeps its position and is the left edge of the pair, the date is aligned to the
    // baseline of the name so both sit on the same line.
    // lv_obj_get_x/y() would return the coordinates of the last layout pass (still 0 while the
    // widget tree is built and filled in the same tick), the values lv_obj_set_pos() wrote are
    // the style properties.
    // The pair is moved with the translation styles and NOT with lv_obj_set_pos(): the style x/y
    // has to keep the position the labels were created with. lv_obj_set_pos() would store the
    // centered position in the style, the next call would use it as the new left edge of the pair
    // and the pair would move one step further out of the row with every update - the screens
    // refresh once per second, so it is out of the window after a few seconds
    const auto left = lv_obj_get_style_x(name, LV_PART_MAIN);
    const auto top = lv_obj_get_style_y(name, LV_PART_MAIN);
    const auto dateLeft = lv_obj_get_style_x(date, LV_PART_MAIN);
    const auto dateTop = lv_obj_get_style_y(date, LV_PART_MAIN);
    const auto x = static_cast<lv_coord_t>(LV_COORD_IS_SPEC(left) ? 0 : left);
    const auto y = static_cast<lv_coord_t>(LV_COORD_IS_SPEC(top) ? 0 : top);
    const auto offset = static_cast<lv_coord_t>((width - nameWidth - gap - dateWidth) / 2);
    lv_obj_set_style_translate_x(name, offset, LV_PART_MAIN);
    lv_obj_set_style_translate_y(name, 0, LV_PART_MAIN);
    lv_obj_set_style_translate_x(date,
                                 static_cast<lv_coord_t>(x + offset + nameWidth + gap - (LV_COORD_IS_SPEC(dateLeft) ? 0 : dateLeft)),
                                 LV_PART_MAIN);
    lv_obj_set_style_translate_y(date,
                                 static_cast<lv_coord_t>(y + _baseline(nameFont) - _baseline(dateFont) - (LV_COORD_IS_SPEC(dateTop) ? 0 : dateTop)),
                                 LV_PART_MAIN);
    lv_label_set_text(name, nameText);
    lv_label_set_text(date, dateText);
}

void setText(lv_obj_t *label, const char *text, const lv_font_t *font, uint32_t color)
{
    if (!label) {
        return;
    }
    if (font) {
        lv_obj_set_style_text_font(label, font, LV_PART_MAIN);
    }
    lv_obj_set_style_text_color(label, lv_color_hex(color), LV_PART_MAIN);
    lv_label_set_text(label, text ? text : "");
}

// ------------------------------------------------------------------------------------------
// widgets
// ------------------------------------------------------------------------------------------
// vertical position of the clock in the top bar and the gap between its labels
static constexpr lv_coord_t kClockTop = 4;
static constexpr lv_coord_t kClockGap = 10;
static constexpr lv_coord_t kClockMargin = 10;
// room for the title on the left side of the top bar (a longer title shrinks)
static constexpr lv_coord_t kTitleWidth = 150;
// the info text starts here and ends before the clock
static constexpr lv_coord_t kInfoX = 168;
static constexpr lv_coord_t kClockReserve = 240;

// places date, time and the time zone next to each other at the right end of the top bar. The
// date and the time zone are baseline aligned with the (larger) time
void _alignClock(const PageRefs &page)
{
    if (!page.date || !page.time || !page.zone) {
        return;
    }
    const auto dateWidth = getTextWidth(lv_label_get_text(page.date), kFontNormal);
    const auto timeWidth = getTextWidth(lv_label_get_text(page.time), kFontTitle);
    const auto zoneWidth = getTextWidth(lv_label_get_text(page.zone), kFontNormal);
    auto x = static_cast<lv_coord_t>(lv_disp_get_hor_res(nullptr) - kClockMargin -
                                     (dateWidth + kClockGap + timeWidth + kClockGap + zoneWidth));
    const auto titleTop = static_cast<lv_coord_t>(kClockTop + _baseline(kFontTitle) - _baseline(kFontNormal));

    lv_obj_set_pos(page.date, x, titleTop);
    x = static_cast<lv_coord_t>(x + dateWidth + kClockGap);
    lv_obj_set_pos(page.time, x, kClockTop);
    x = static_cast<lv_coord_t>(x + timeWidth + kClockGap);
    lv_obj_set_pos(page.zone, x, titleTop);
}

PageRefs createPage(lv_obj_t *parent, const char *title, const char *right)
{
    PageRefs page;
    if (!parent) {
        return page;
    }
    page.root = parent;
    lv_obj_clear_flag(parent, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(parent, lv_color_hex(kColorBackground), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(parent, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_pad_all(parent, 0, LV_PART_MAIN);

    // top bar: title on the left, clock on the right
    auto bar = _container(parent, 0, 0, LV_PCT(100), kBarHeight);
    lv_obj_set_style_bg_color(bar, lv_color_hex(kColorBar), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(bar, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_border_side(bar, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN);
    lv_obj_set_style_border_width(bar, 1, LV_PART_MAIN);
    lv_obj_set_style_border_color(bar, lv_color_hex(kColorTextMuted), LV_PART_MAIN);
    lv_obj_set_style_border_opa(bar, LV_OPA_50, LV_PART_MAIN);
    lv_obj_set_width(bar, lv_disp_get_hor_res(nullptr));
    // the screen manager handles the taps of the bar (they open the screen overview), no widget
    // inside it needs to be clickable
    lv_obj_clear_flag(bar, LV_OBJ_FLAG_CLICKABLE);

    page.title = lv_label_create(bar);
    lv_obj_set_style_text_font(page.title, kFontMedium, LV_PART_MAIN);
    lv_obj_set_style_text_color(page.title, lv_color_hex(kColorTextLabel), LV_PART_MAIN);
    lv_obj_set_width(page.title, kTitleWidth);
    lv_label_set_text(page.title, title ? title : "");
    fitTextDown(page.title, title ? title : "", kTitleWidth);
    lv_obj_align(page.title, LV_ALIGN_LEFT_MID, 10, 0);

    if (right) {
        page.info = lv_label_create(bar);
        lv_obj_set_style_text_font(page.info, kFontSmall, LV_PART_MAIN);
        lv_obj_set_style_text_color(page.info, lv_color_hex(kColorTextMuted), LV_PART_MAIN);
        // one line between the title and the clock, a longer text is cut off
        fitTextDown(page.info, right, static_cast<lv_coord_t>(lv_disp_get_hor_res(nullptr) - kClockReserve - kInfoX));
        lv_obj_align(page.info, LV_ALIGN_LEFT_MID, kInfoX, 0);
    }

    page.date = lv_label_create(bar);
    lv_obj_set_style_text_font(page.date, kFontNormal, LV_PART_MAIN);
    lv_obj_set_style_text_color(page.date, lv_color_hex(kColorTextValue), LV_PART_MAIN);
    lv_label_set_text(page.date, "--");

    page.time = lv_label_create(bar);
    lv_obj_set_style_text_font(page.time, kFontTitle, LV_PART_MAIN);
    lv_obj_set_style_text_color(page.time, lv_color_hex(kColorText), LV_PART_MAIN);
    lv_label_set_text(page.time, "--:--");

    page.zone = lv_label_create(bar);
    lv_obj_set_style_text_font(page.zone, kFontNormal, LV_PART_MAIN);
    lv_obj_set_style_text_color(page.zone, lv_color_hex(kColorHighlight), LV_PART_MAIN);
    lv_label_set_text(page.zone, "");
    _alignClock(page);
    return page;
}

// one part of the clock, written into the buffer of the caller (nothing is written for a nullptr)
static void _formatClockPart(const char *format, struct tm &tm, char *output, size_t size)
{
    if (!output || !size) {
        return;
    }
    if (strftime(output, size, format, &tm) <= 0) {
        output[0] = 0;
    }
}

void formatClock(bool format24h, char *date, size_t dateSize, char *time, size_t timeSize, char *zone, size_t zoneSize)
{
    if (date && dateSize) {
        date[0] = 0;
    }
    if (time && timeSize) {
        time[0] = 0;
    }
    if (zone && zoneSize) {
        zone[0] = 0;
    }
    auto now = ::time(nullptr);
    if (now < 1600000000) { // clock not set yet (before 2020)
        return;
    }
    struct tm tm;
    localtime_r(&now, &tm);
    _formatClockPart("%a %b %d %Y", tm, date, dateSize);
    _formatClockPart(format24h ? "%H:%M" : "%I:%M %p", tm, time, timeSize);
    _formatClockPart("%Z", tm, zone, zoneSize);
}

void formatClock(bool format24h, String &date, String &time, String &zone)
{
    char dateBuffer[40];
    char timeBuffer[40];
    char zoneBuffer[40];
    formatClock(format24h, dateBuffer, sizeof(dateBuffer), timeBuffer, sizeof(timeBuffer), zoneBuffer, sizeof(zoneBuffer));
    date = dateBuffer;
    time = timeBuffer;
    zone = zoneBuffer;
}

void setClock(const PageRefs &page, bool format24h)
{
    if (!page.isValid()) {
        return;
    }
    String date;
    String time;
    String zone;
    formatClock(format24h, date, time, zone);
    if (page.date) {
        lv_label_set_text(page.date, date.length() ? date.c_str() : "--");
    }
    if (page.time) {
        lv_label_set_text(page.time, time.length() ? time.c_str() : "--:--");
    }
    if (page.zone) {
        lv_label_set_text(page.zone, zone.c_str());
    }
    // the labels are right aligned next to each other, their width changed with the text
    _alignClock(page);
}

lv_obj_t *createFooter(lv_obj_t *parent)
{
    auto height = static_cast<lv_coord_t>(lv_obj_get_height(parent) - kFooterHeight);
    auto footer = _container(parent, 0, height, LV_PCT(100), kFooterHeight);
    lv_obj_set_style_bg_color(footer, lv_color_hex(kColorBar), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(footer, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_border_side(footer, LV_BORDER_SIDE_TOP, LV_PART_MAIN);
    lv_obj_set_style_border_width(footer, 1, LV_PART_MAIN);
    lv_obj_set_style_border_color(footer, lv_color_hex(kColorTextMuted), LV_PART_MAIN);
    lv_obj_set_style_border_opa(footer, LV_OPA_50, LV_PART_MAIN);
    return footer;
}

lv_obj_t *createContainer(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h)
{
    return _container(parent, x, y, w, h);
}

lv_obj_t *createCard(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h,
                     const char *title)
{
    auto card = lv_obj_create(parent);
    lv_obj_set_pos(card, x, y);
    lv_obj_set_size(card, w, h);
    lv_obj_clear_flag(card, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(card, lv_color_hex(kColorCard), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(card, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_radius(card, kCardRadius, LV_PART_MAIN);
    lv_obj_set_style_border_width(card, 1, LV_PART_MAIN);
    lv_obj_set_style_border_color(card, lv_color_hex(kColorBorder), LV_PART_MAIN);
    lv_obj_set_style_pad_all(card, 0, LV_PART_MAIN);
    lv_obj_set_style_shadow_width(card, 0, LV_PART_MAIN);
    if (title) {
        auto label = lv_label_create(card);
        lv_obj_set_pos(label, 10, 8);
        lv_obj_set_style_text_font(label, kFontNormal, LV_PART_MAIN);
        lv_obj_set_style_text_color(label, lv_color_hex(kColorTextLabel), LV_PART_MAIN);
        lv_label_set_text(label, title);
    }
    return card;
}

lv_obj_t *addLabel(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, const char *text,
                   const lv_font_t *font, uint32_t color, lv_coord_t maxWidth, lv_text_align_t align)
{
    auto label = lv_label_create(parent);
    lv_obj_set_pos(label, x, y);
    lv_obj_set_style_text_font(label, font, LV_PART_MAIN);
    lv_obj_set_style_text_color(label, lv_color_hex(color), LV_PART_MAIN);
    if (maxWidth != LV_SIZE_CONTENT) {
        lv_obj_set_width(label, maxWidth);
        lv_obj_set_style_text_align(label, align, LV_PART_MAIN);
    }
    lv_label_set_text(label, text ? text : "");
    return label;
}

lv_obj_t *addSeparator(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w)
{
    auto line = _container(parent, x, y, w, 1);
    lv_obj_set_style_bg_color(line, lv_color_hex(kColorBorder), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(line, LV_OPA_COVER, LV_PART_MAIN);
    return line;
}

KeyValueRefs addKeyValue(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t gap,
                         const char *key, const char *value, lv_coord_t keyWidth)
{
    KeyValueRefs refs;
    // the key never takes more than half of the row, a longer key is cut off
    const auto maxKeyWidth = static_cast<lv_coord_t>((w - gap) / 2);
    if (keyWidth <= 0) {
        keyWidth = static_cast<lv_coord_t>((w - gap) * 0.45f);
    }
    if (keyWidth > maxKeyWidth) {
        keyWidth = maxKeyWidth;
    }
    auto valueWidth = static_cast<lv_coord_t>(w - gap - keyWidth);
    refs.key = addLabel(parent, x, y, key, kFontNormal, kColorTextLabel, keyWidth);
    fitTextDown(refs.key, key, keyWidth);
    refs.value = addLabel(parent, static_cast<lv_coord_t>(x + keyWidth + gap), y, value, kFontNormal,
                          kColorText, valueWidth, LV_TEXT_ALIGN_RIGHT);
    // the value shrinks first, but it must not grow either: the rows of a key/value list are
    // already laid out and mixing font sizes looks broken (the row height is fixed)
    fitTextDown(refs.value, value, valueWidth);
    // a row is one line, a long value must be cut off instead of wrapping into the next row
    lv_obj_set_height(refs.key, lv_font_get_line_height(kFontNormal));
    lv_obj_set_height(refs.value, lv_font_get_line_height(kFontNormal));
    return refs;
}

// ------------------------------------------------------------------------------------------
// tiles, arcs and buttons (application dashboards)
// ------------------------------------------------------------------------------------------
// A tile of a dashboard has no outline: the reviewed layouts (docs/hass_layout) draw a plain
// card, the state is the fill (setTileState) and the text/glyph color. LVGLUI::createCard() is
// the variant with a 1 px kColorBorder outline, used by the pages of the screen overview.
lv_obj_t *createTile(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h)
{
    auto tile = createCard(parent, x, y, w, h);
    lv_obj_set_style_bg_color(tile, lv_color_hex(kColorCard), LV_PART_MAIN);
    lv_obj_set_style_border_width(tile, 0, LV_PART_MAIN);
    return tile;
}

void setTileState(lv_obj_t *tile, TileState state, bool filled)
{
    if (!tile) {
        return;
    }
    auto border = kColorBorder;
    auto background = kColorCard;
    switch (state) {
    case TileState::ON:
        border = kColorActive;
        if (filled) {
            // an active tile is a filled card, the texts are drawn white by the screen
            background = kColorActive;
        }
        break;
    case TileState::PENDING:
        // An action is on its way: the accent border is the mark. The fill follows the state the
        // tile shows - the action was applied to the model right away (optimistic, see
        // Dashboard::toggle()), so a tile that the user switched on is filled while the entity has
        // not confirmed it yet (filled = the tile shows an active state)
        border = kColorAccent;
        background = filled ? kColorActive : kColorCardAlt;
        break;
    case TileState::UNAVAILABLE:
        // darker card: a tile has no outline, the mark has to be the fill
        border = kColorError;
        background = kColorCardAlt;
        break;
    default:
        break;
    }
    lv_obj_set_style_border_color(tile, lv_color_hex(border), LV_PART_MAIN);
    lv_obj_set_style_bg_color(tile, lv_color_hex(background), LV_PART_MAIN);
}

lv_obj_t *createImage(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h)
{
    auto image = lv_img_create(parent);
    lv_obj_set_pos(image, x, y);
    lv_obj_set_size(image, w, h);
    lv_obj_clear_flag(image, LV_OBJ_FLAG_SCROLLABLE);
    // the tile around the image handles a tap
    lv_obj_clear_flag(image, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_pad_all(image, 0, LV_PART_MAIN);
    lv_obj_set_style_radius(image, 0, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(image, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_border_width(image, 0, LV_PART_MAIN);
    return image;
}

lv_obj_t *createArc(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t size, lv_coord_t ringWidth)
{
    auto arc = lv_arc_create(parent);
    lv_obj_set_pos(arc, x, y);
    lv_obj_set_size(arc, size, size);
    // 270 degrees with the gap centered at the bottom
    lv_arc_set_rotation(arc, kArcRotation);
    lv_arc_set_bg_angles(arc, 0, 270);
    lv_arc_set_range(arc, 0, 100);
    lv_arc_set_value(arc, 0);

    lv_obj_set_style_bg_opa(arc, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_border_width(arc, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_all(arc, 0, LV_PART_MAIN);
    lv_obj_set_style_arc_width(arc, ringWidth, LV_PART_MAIN);
    lv_obj_set_style_arc_color(arc, lv_color_hex(kColorBorder), LV_PART_MAIN);
    lv_obj_set_style_arc_width(arc, ringWidth, LV_PART_INDICATOR);
    lv_obj_set_style_arc_color(arc, lv_color_hex(kColorAccent), LV_PART_INDICATOR);
    lv_obj_set_style_bg_color(arc, lv_color_hex(kColorAccent), LV_PART_KNOB);
    lv_obj_set_style_bg_opa(arc, LV_OPA_COVER, LV_PART_KNOB);
    // The knob is a circle of arc_width + 2 x pad (get_knob_area() of lv_arc.c), so the white dot
    // is exactly as thick as the ring with a padding of 0. A larger padding makes it a ball that
    // sticks out of the ring
    lv_obj_set_style_pad_all(arc, 0, LV_PART_KNOB);
    return arc;
}

void setArcValue(lv_obj_t *arc, int16_t value, uint32_t color)
{
    if (!arc) {
        return;
    }
    lv_arc_set_value(arc, value);
    lv_obj_set_style_arc_color(arc, lv_color_hex(color), LV_PART_INDICATOR);
    // the knob is white, like the handle of the Home Assistant thermostat card
    lv_obj_set_style_bg_color(arc, lv_color_hex(kColorText), LV_PART_KNOB);
}

lv_obj_t *createButton(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h,
                       const char *text, const lv_font_t *font)
{
    auto button = _container(parent, x, y, w, h);
    lv_obj_set_style_radius(button, 6, LV_PART_MAIN);
    lv_obj_set_style_bg_color(button, lv_color_hex(kColorCardAlt), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(button, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_border_width(button, 1, LV_PART_MAIN);
    lv_obj_set_style_border_color(button, lv_color_hex(kColorBorder), LV_PART_MAIN);
    if (text && *text) {
        auto label = lv_label_create(button);
        lv_label_set_text(label, text);
        lv_obj_set_style_text_font(label, font ? font : kFontSmall, LV_PART_MAIN);
        lv_obj_set_style_text_color(label, lv_color_hex(kColorTextValue), LV_PART_MAIN);
        lv_obj_center(label);
    }
    return button;
}

void setButtonActive(lv_obj_t *button, bool active)
{
    if (!button) {
        return;
    }
    // the active segment of a control bar is filled, like the buttons of the Home Assistant
    // thermostat card
    lv_obj_set_style_bg_color(button, lv_color_hex(active ? kColorActive : kColorCardAlt), LV_PART_MAIN);
    lv_obj_set_style_border_color(button, lv_color_hex(active ? kColorActive : kColorBorder), LV_PART_MAIN);
    auto child = lv_obj_get_child(button, 0);
    if (child && lv_obj_check_type(child, &lv_label_class)) {
        lv_obj_set_style_text_color(child, lv_color_hex(active ? kColorBackground : kColorTextValue), LV_PART_MAIN);
    }
}

// ------------------------------------------------------------------------------------------
// level fill and lists of the dashboards
// ------------------------------------------------------------------------------------------
lv_obj_t *createLevelFill(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h)
{
    auto fill = _container(parent, x, y, w, h);
    // only the edge that follows the level is a shape of its own: the corners at the other end are
    // clipped by the rounded tile the fill lives in (the tile sets LV_OBJ_FLAG_CLIP_CORNER), so the
    // fill stays flush with the tile there
    lv_obj_set_style_radius(fill, kLevelFillRadius, LV_PART_MAIN);
    lv_obj_set_style_bg_color(fill, lv_color_hex(kColorActive), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(fill, LV_OPA_COVER, LV_PART_MAIN);
    return fill;
}

void setLevelFill(lv_obj_t *fill, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t trackHeight,
                  uint8_t percent, uint32_t color)
{
    if (!fill) {
        return;
    }
    if (percent > 100) {
        percent = 100;
    }
    const auto height = static_cast<lv_coord_t>((trackHeight * percent) / 100);
    lv_obj_set_pos(fill, x, static_cast<lv_coord_t>(y + trackHeight - height));
    lv_obj_set_size(fill, w, height);
    lv_obj_set_style_bg_color(fill, lv_color_hex(color), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(fill, height ? LV_OPA_COVER : LV_OPA_TRANSP, LV_PART_MAIN);
}

lv_obj_t *createList(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h)
{
    auto list = _container(parent, x, y, w, h);
    lv_obj_set_style_bg_color(list, lv_color_hex(kColorCard), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(list, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_border_width(list, 1, LV_PART_MAIN);
    lv_obj_set_style_border_color(list, lv_color_hex(kColorBorder), LV_PART_MAIN);
    lv_obj_set_style_radius(list, kCardRadius, LV_PART_MAIN);
    // the items are children of a scrollable container, the scrollbar is 6 px on the right
    lv_obj_set_style_pad_all(list, 4, LV_PART_MAIN);
    lv_obj_set_style_pad_right(list, 10, LV_PART_MAIN);
    lv_obj_add_flag(list, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scroll_dir(list, LV_DIR_VER);
    lv_obj_set_scrollbar_mode(list, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_set_style_width(list, 6, LV_PART_SCROLLBAR);
    lv_obj_set_style_radius(list, LV_RADIUS_CIRCLE, LV_PART_SCROLLBAR);
    lv_obj_set_style_bg_color(list, lv_color_hex(kColorBorder), LV_PART_SCROLLBAR);
    lv_obj_set_style_bg_opa(list, LV_OPA_COVER, LV_PART_SCROLLBAR);
    return list;
}

// left and right margin between the label and the item of a list: a name that is shortened with
// dots keeps that distance to the rounded corners of the card
static constexpr lv_coord_t kListItemLabelMargin = 6;
// Spaces of the item font the glyph of an item keeps to the left edge of the item and to the name
// behind it (the spacing of the reviewed option lists, measured with the font so that it scales
// with it)
static constexpr uint8_t kListItemIconSpaces = 3;

// implementation of both addListItem() overloads, `icon` is nullptr while the item has no icon
static lv_obj_t *_addListItem(lv_obj_t *list, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h,
                              const char *text, const IconType *icon)
{
    auto item = createButton(list, x, y, w, h, text, kFontNormal);
    // an item looks like a tile of the grid, not like a control of a bar: the card color of a tile
    // and no outline
    lv_obj_set_style_radius(item, kCardRadius, LV_PART_MAIN);
    lv_obj_set_style_bg_color(item, lv_color_hex(kColorCard), LV_PART_MAIN);
    lv_obj_set_style_border_width(item, 0, LV_PART_MAIN);

    auto label = lv_obj_get_child(item, 0);
    if (!label || !lv_obj_check_type(label, &lv_label_class)) {
        return item;
    }
    const auto font = lv_obj_get_style_text_font(label, LV_PART_MAIN);
    const auto lineHeight = lv_font_get_line_height(font);
    // An item without a glyph is a centered name. With a glyph the name is left aligned behind it:
    // the glyph, three spaces of the item font away from the left edge of the item, then the name
    // three spaces behind the glyph. A name that does not fit into the room right of the glyph is
    // shortened with dots - LV_LABEL_LONG_DOT needs the box of its own to measure against (the
    // label of createButton() is only as wide as its text and LVGL would simply clip it at the edge
    // of the item)
    auto labelX = kListItemLabelMargin;
    auto labelW = static_cast<lv_coord_t>(w - 2 * kListItemLabelMargin);
    auto textAlign = LV_TEXT_ALIGN_CENTER;
    if (icon) {
        const auto gap = static_cast<lv_coord_t>(getTextWidth(" ", font) * kListItemIconSpaces);
        labelX = static_cast<lv_coord_t>(gap + kIconSizeSmall + gap);
        labelW = static_cast<lv_coord_t>(w - labelX - gap);
        if (labelW < 8) {
            labelW = 8;
        }
        textAlign = LV_TEXT_ALIGN_LEFT;
        auto iconObj = createIcon(item, *icon, gap, static_cast<lv_coord_t>((h - kIconSizeSmall) / 2),
                                  kIconSizeSmall, kColorTextValue);
        // the glyph is not a control of its own: without this a tap in the middle of the icon hits
        // the icon and the item never receives its click
        clearClickable(iconObj);
    }
    // The text of a label is aligned to the left by default, which the box of a name that is not
    // shortened turns into a left aligned item (createButton() centered the text by centering its
    // auto sized label). LVGL aligns the dots of a shortened name to the alignment as well.
    // lv_obj_align(LV_ALIGN_DEFAULT) and not lv_obj_set_pos(): createButton() centered the label
    // with lv_obj_center(), which left the alignment of the object set - a position would be added
    // to that alignment and the box would land half an item beside the glyph
    lv_obj_set_style_text_align(label, textAlign, LV_PART_MAIN);
    lv_obj_set_size(label, labelW, lineHeight);
    lv_obj_align(label, LV_ALIGN_DEFAULT, labelX, static_cast<lv_coord_t>((h - lineHeight) / 2));
    lv_label_set_long_mode(label, LV_LABEL_LONG_DOT);
    return item;
}

lv_obj_t *addListItem(lv_obj_t *list, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h, const char *text)
{
    return _addListItem(list, x, y, w, h, text, nullptr);
}

void setListItemActive(lv_obj_t *item, bool active)
{
    if (!item) {
        return;
    }
    // a filled (active) item looks like an active tile, the others are plain tiles
    lv_obj_set_style_bg_color(item, lv_color_hex(active ? kColorActive : kColorCard), LV_PART_MAIN);
    lv_obj_set_style_border_color(item, lv_color_hex(active ? kColorActive : kColorCard), LV_PART_MAIN);
    // the label and the glyph in front of it draw the color of the item
    for (uint32_t i = 0; i < lv_obj_get_child_cnt(item); i++) {
        auto child = lv_obj_get_child(item, i);
        if (lv_obj_check_type(child, &lv_label_class)) {
            lv_obj_set_style_text_color(child, lv_color_hex(active ? kColorText : kColorTextValue), LV_PART_MAIN);
        }
        else {
            setIconColor(child, active ? kColorText : kColorTextValue);
        }
    }
}

void clearClickable(lv_obj_t *obj)
{
    if (!obj) {
        return;
    }
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_CLICKABLE);
    const auto count = lv_obj_get_child_cnt(obj);
    for (uint32_t i = 0; i < count; i++) {
        clearClickable(lv_obj_get_child(obj, i));
    }
}

// ------------------------------------------------------------------------------------------
// icons
// ------------------------------------------------------------------------------------------
lv_obj_t *createIcon(lv_obj_t *parent, IconType type, lv_coord_t x, lv_coord_t y, lv_coord_t size,
                     uint32_t color)
{
    auto icon = _container(parent, x, y, size, size);
    _drawIcon(icon, type, size, color);
    return icon;
}

void setIcon(lv_obj_t *icon, IconType type, lv_coord_t size, uint32_t color)
{
    if (!icon) {
        return;
    }
    lv_obj_clean(icon);
    lv_obj_set_size(icon, size, size);
    _drawIcon(icon, type, size, color);
}

bool isIcon(lv_obj_t *icon, IconType type)
{
    const auto index = static_cast<uint8_t>(type);
    if (!icon || index >= kIconCount) {
        return false;
    }
    // the glyph is the only child of an icon container, see _drawIcon()
    auto label = lv_obj_get_child(icon, 0);
    if (!label) {
        return false;
    }
    const auto *text = lv_label_get_text(label);
    return text && strcmp(text, kIconGlyph[index]) == 0;
}

// the glyph is the only child of an icon container
void setIconColor(lv_obj_t *icon, uint32_t color)
{
    if (!icon) {
        return;
    }
    auto label = lv_obj_get_child(icon, 0);
    if (label) {
        lv_obj_set_style_text_color(label, lv_color_hex(color), LV_PART_MAIN);
    }
}

lv_obj_t *createIconButton(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h,
                           IconType type, lv_coord_t iconSize)
{
    auto button = createButton(parent, x, y, w, h, nullptr);
    auto icon = createIcon(button, type, static_cast<lv_coord_t>((w - iconSize) / 2), static_cast<lv_coord_t>((h - iconSize) / 2), iconSize);
    // the glyph is not a control of its own: without this a tap in the middle of the button hits the
    // icon and the button never receives its click
    clearClickable(icon);
    return button;
}

lv_obj_t *addListItem(lv_obj_t *list, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h, const char *text,
                      IconType icon)
{
    return _addListItem(list, x, y, w, h, text, &icon);
}

lv_obj_t *createHouseIcon(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t size)
{
    return createIcon(parent, IconType::HOUSE, x, y, size);
}

// Rotation: a 300 degree arc with the gap on the right and the head of the arrow beside it. The MDI
// subset fonts have no glyph for it, a circular arrow is a few arcs of LVGL
lv_obj_t *createRotateIcon(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t size, uint32_t color)
{
    auto icon = _container(parent, x, y, size, size);
    lv_obj_clear_flag(icon, LV_OBJ_FLAG_CLICKABLE);
    const auto band = static_cast<lv_coord_t>((size >= 32) ? 5 : 2);
    auto arc = lv_arc_create(icon);
    lv_obj_set_size(arc, size, size);
    lv_obj_set_pos(arc, 0, 0);
    // the gap is on the right side, where the head of the arrow sits
    lv_arc_set_rotation(arc, 45);
    lv_arc_set_bg_angles(arc, 0, 300);
    lv_arc_set_mode(arc, LV_ARC_MODE_NORMAL);
    lv_arc_set_value(arc, 0);
    lv_obj_set_style_arc_width(arc, band, LV_PART_MAIN);
    lv_obj_set_style_arc_color(arc, lv_color_hex(color), LV_PART_MAIN);
    lv_obj_set_style_arc_width(arc, 0, LV_PART_INDICATOR);
    lv_obj_set_style_bg_opa(arc, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_border_width(arc, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_all(arc, 0, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(arc, LV_OPA_TRANSP, LV_PART_KNOB);
    lv_obj_set_style_pad_all(arc, 0, LV_PART_KNOB);
    lv_obj_clear_flag(arc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(arc, LV_OBJ_FLAG_SCROLLABLE);
    // the head of the arrow, at the upper end of the arc (45 + 300 = 345 degrees)
    const auto head = band * 3;
    auto disc = _disc(icon, static_cast<lv_coord_t>(size - head), static_cast<lv_coord_t>(size / 2 - head), head, color);
    lv_obj_clear_flag(disc, LV_OBJ_FLAG_CLICKABLE);
    return icon;
}

lv_obj_t *createMoon(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t size)
{
    return _moon(parent, x, y, size);
}

void setMoonPhase(lv_obj_t *moon, float illumination, bool waxing)
{
    if (!moon || lv_obj_get_child_cnt(moon) == 0) {
        return;
    }
    if (illumination < 0) {
        illumination = 0;
    }
    else if (illumination > 1) {
        illumination = 1;
    }
    auto shadow = lv_obj_get_child(moon, 0);
    // lv_obj_get_width() is the size of the last layout pass and 0 while the widget tree was not
    // laid out yet - the screen is created and filled in the same tick, so the disc would not move
    // for the first update. createMoon() sets the size of the disc explicitly, use that one
    auto size = _explicitWidth(moon);
    if (size <= 0) {
        return;
    }
    // waxing = lit on the right, the shadow moves to the left (and out of the disc for a full moon)
    auto offset = static_cast<lv_coord_t>(size * illumination * (waxing ? -2.0f : 2.0f));
    lv_obj_set_pos(shadow, offset, 0);
}

} // namespace LVGLUI

#endif
