
#pragma once
#include "nvs.h"

// CONFIG_UNITY_ENABLE_IDF_TEST_RUNNER=0
// CONFIG_COMPILER_HIDE_PATHS_MACROS=0
// CONFIG_IDF_TARGET="linux"
// CONFIG_COMPILER_CXX_EXCEPTIONS=n
// CONFIG_NVS_ASSERT_ERROR_CHECK=m

