#
# Author: sascha_lammers@gmx.de
#

"""KFC firmware build number generator.

The persistent counter and its history live in a plain text file that is only used by the build
system. It is never compiled and never uploaded - it is a readable log for humans (and AI) to see
which build was compiled when and for which environment(s):

    include/build_number.txt

The compiled build number is written into a single generated translation unit:

    src/build_number.cpp

Keeping the number in one .cpp means a new build recompiles only that file instead of every source
that used to include the old build.h. The firmware version string is a single flash string and the
build number is its suffix, so both share the same flash location.

The counter is incremented before the firmware is compiled, so the new number ends up in the binary,
and the generated src/build_number.cpp is written in the same step. A build that never reaches the
link step did not create a firmware, its number is taken back on the next run. The history is kept
forever.
"""

import argparse
import datetime
import os
import re
import sys
import time

DEFAULT_COUNTER = os.path.join('include', 'build_number.txt')
DEFAULT_OUTPUT = os.path.join('src', 'build_number.cpp')
# written when a build starts, removed by the build after the firmware was linked
DEFAULT_PENDING = os.path.join('.pio', 'build_number.pending')

COUNTER_HEADER = """; -------------------------------------------------------------------------
; KFC firmware build number
;
; maintained by scripts/build_number.py - do not edit manually
; "number" is the build that is currently being compiled
; -------------------------------------------------------------------------

number = {number}
date   = {date}
env    = {env}

; history, newest first: <number> <date> <time> <environments>
"""

# the only translation unit that knows the build number, see module docstring
CPP_TEMPLATE = '''/**
 * Generated by scripts/build_number.py - do not edit
 *
 * build {number}
 * date  {date}
 */

#include <Arduino_compat.h>
#include "kfc_fw_config.h"

// the complete short firmware version as a single flash string, e.g. "0.0.9 Build {number}"
// the build number below is the suffix of this string and shares its flash location
static const char __firmware_short_version[] PROGMEM = FIRMWARE_VERSION_STR " Build " "{number}";

const __FlashStringHelper *KFCFWConfiguration::getShortFirmwareVersion()
{{
    return FPSTR(__firmware_short_version);
}}

const __FlashStringHelper *KFCFWConfiguration::getBuildNumberString()
{{
    return FPSTR(__firmware_short_version + (sizeof(FIRMWARE_VERSION_STR " Build ") - 1));
}}

uint32_t KFCFWConfiguration::getBuildNumber()
{{
    return {number};
}}

const __FlashStringHelper *KFCFWConfiguration::getFirmwareVersion()
{{
    #if ESP32
        return F(FIRMWARE_VERSION_STR " Build " "{number}" "-" ARDUINO_ESP32_RELEASE " " __DATE__ " " __TIME__);
    #elif ESP8266
        return F(FIRMWARE_VERSION_STR " Build " "{number}" "-" ARDUINO_ESP8266_RELEASE " " __DATE__ " " __TIME__);
    #else
        return F(FIRMWARE_VERSION_STR " Build " "{number}" " " __DATE__ " " __TIME__);
    #endif
}}
'''

HISTORY_LINE_RE = re.compile(r'^(?P<number>\d+)[ \t]+(?P<date>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})(?:[ \t]+(?P<env>.*))?$')


def get_date(timestamp=None):
    return datetime.datetime.fromtimestamp(timestamp if timestamp is not None else time.time()).strftime('%Y-%m-%d %H:%M:%S')


def split_envs(env):
    return [item.strip() for item in re.split(r'\s*,\s*', env or '') if item.strip()]


def join_envs(envs):
    if isinstance(envs, str):
        envs = split_envs(envs)
    result = []
    for env in envs:
        if env and env not in result:
            result.append(env)
    return ', '.join(result)


def read_counter(filename, initial=0):
    """Return (number, date, history) from the plain text counter file."""
    number = initial
    date = ''
    history = []
    if os.path.isfile(filename):
        with open(filename, 'rt', encoding='utf-8') as file:
            content = file.read()
        match = re.search(r'^[ \t]*number[ \t]*=[ \t]*(\d+)', content, re.M)
        if match:
            number = int(match.group(1))
        match = re.search(r'^[ \t]*date[ \t]*=[ \t]*(.*?)[ \t]*$', content, re.M)
        if match:
            date = match.group(1)
        for line in content.splitlines():
            match = HISTORY_LINE_RE.match(line.strip())
            if match:
                history.append((
                    int(match.group('number')),
                    match.group('date'),
                    (match.group('env') or '').strip(),
                ))
    return number, date, history


def render_counter(number, date, envs, history):
    lines = [COUNTER_HEADER.format(number=number, date=date, env=join_envs(envs)).rstrip('\n')]
    for entry_number, entry_date, entry_env in history:
        line = '%d %s' % (entry_number, entry_date)
        if entry_env:
            line += ' ' + entry_env
        lines.append(line)
    return '\n'.join(lines).rstrip('\n') + '\n'


def render_cpp(number, date):
    return CPP_TEMPLATE.format(number=number, date=date)


def write_file(filename, content):
    directory = os.path.dirname(os.path.abspath(filename))
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(filename, 'wt', encoding='utf-8', newline='\n') as file:
        file.write(content)


def read_pending(filename):
    """Build number of a build that started but never reached the link step, otherwise 0."""
    try:
        with open(filename, 'rt', encoding='utf-8') as file:
            return int(file.read().split()[0])
    except Exception:
        return 0


def write_pending(filename, number):
    write_file(filename, '%d\n' % number)


def remove_file(filename):
    try:
        os.remove(filename)
    except OSError:
        pass


def main(argv=None):
    parser = argparse.ArgumentParser(
        description='KFC firmware build number generator',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument('--project-dir', default=os.getcwd(), help='project directory (default: the current directory)')
    parser.add_argument('--counter', default=None, help='counter and history file (default: %s)' % DEFAULT_COUNTER)
    parser.add_argument('-o', '--output', default=None, help='generated C++ file (default: %s)' % DEFAULT_OUTPUT)
    parser.add_argument('--pending', default=None, help='marker of a build that has not been linked yet (default: %s)' % DEFAULT_PENDING)
    parser.add_argument('--env', action='append', default=[], help='environment that is being built, repeatable')
    parser.add_argument('--commit', action='store_true', help='the firmware was linked and the number stays')
    parser.add_argument('--force', action='store_true', help='increment without a pending build, used by -t newbuild')
    parser.add_argument('--print-number', action='store_true', help='print the current build number and exit')
    parser.add_argument('--print-contents', action='store_true', help='print the generated C++ file and exit')
    parser.add_argument('-v', '--verbose', action='store_true', help='verbose output')
    args = parser.parse_args(argv)

    project_dir = os.path.abspath(args.project_dir)
    counter_file = args.counter or os.path.join(project_dir, DEFAULT_COUNTER)
    output_file = args.output or os.path.join(project_dir, DEFAULT_OUTPUT)
    pending_file = args.pending or os.path.join(project_dir, DEFAULT_PENDING)

    number, date, history = read_counter(counter_file)

    if args.print_number:
        print(number)
        return 0

    if args.print_contents:
        print(render_cpp(number + 1, get_date()))
        return 0

    if args.commit:
        # reached the link step, the number stays
        remove_file(pending_file)
        return 0

    # a build that never reached the link step did not produce a firmware, take its number back
    pending = read_pending(pending_file)
    if pending:
        remove_file(pending_file)
        if pending == number:
            if history and history[0][0] == number:
                history.pop(0)
            number -= 1
            date = history[0][1] if history else ''
            if args.verbose:
                print('Build %d did not finish, reusing the number' % pending)

    # increment before compiling so the new number ends up in the firmware
    number += 1
    date = get_date()
    envs = args.env
    history.insert(0, (number, date, join_envs(envs)))

    write_file(counter_file, render_counter(number, date, envs, history))

    cpp = render_cpp(number, date)
    if not os.path.isfile(output_file) or open(output_file, 'rt', encoding='utf-8').read() != cpp:
        write_file(output_file, cpp)

    # the build removes the marker after the firmware was linked
    if args.force:
        remove_file(pending_file)
    else:
        write_pending(pending_file, number)

    if args.verbose:
        print('Build number: %d (%s)' % (number, join_envs(envs)))
    return 0


if __name__ == '__main__':
    sys.exit(main())

