/**
 * Author: sascha_lammers@gmx.de
 *
 * Material Design Icons (MDI) - generated by scripts/tools/fonts/generate_lvgl_fonts.py,
 * do not edit. 53 icons of @mdi/font 7.4.47, the fonts are lv_font_mdi_20/lv_font_mdi_48 in
 * src/plugins/lvgl/fonts/ (see LVGLUI::kIconFonts).
 *
 * The literals are the UTF-8 encoded glyphs, use them with a label that has one of the icon
 * fonts selected (LVGLUI::createIcon()/setIcon()).
 */

#pragma once

// name in the firmware -> glyph (the enumerator of LVGLUI::IconType)

#define LVGL_MDI_SUN             "\xF3\xB0\x96\x99" // mdi-weather-sunny U+F0599
#define LVGL_MDI_PARTLY_CLOUDY   "\xF3\xB0\x96\x95" // mdi-weather-partly-cloudy U+F0595
#define LVGL_MDI_CLOUDY          "\xF3\xB0\x96\x90" // mdi-weather-cloudy U+F0590
#define LVGL_MDI_RAIN            "\xF3\xB0\x96\x97" // mdi-weather-rainy U+F0597
#define LVGL_MDI_SNOW            "\xF3\xB0\x96\x98" // mdi-weather-snowy U+F0598
#define LVGL_MDI_STORM           "\xF3\xB0\x96\x93" // mdi-weather-lightning U+F0593
#define LVGL_MDI_FOG             "\xF3\xB0\x96\x91" // mdi-weather-fog U+F0591
#define LVGL_MDI_UNKNOWN         "\xF3\xB0\x97\x96" // mdi-alert-circle-outline U+F05D6
#define LVGL_MDI_HOUSE           "\xF3\xB0\x8B\x9C" // mdi-home U+F02DC
#define LVGL_MDI_CALENDAR        "\xF3\xB0\x83\xAD" // mdi-calendar U+F00ED
#define LVGL_MDI_MOON            "\xF3\xB0\xBD\xA5" // mdi-moon-waning-crescent U+F0F65
#define LVGL_MDI_INFO            "\xF3\xB0\x8B\xBD" // mdi-information-outline U+F02FD
#define LVGL_MDI_CLOCK           "\xF3\xB0\x85\x90" // mdi-clock-outline U+F0150
#define LVGL_MDI_GLOBE           "\xF3\xB0\x87\xA7" // mdi-earth U+F01E7
#define LVGL_MDI_POWER           "\xF3\xB0\x89\x81" // mdi-flash U+F0241
#define LVGL_MDI_PICTURE         "\xF3\xB0\x8B\xA9" // mdi-image U+F02E9
#define LVGL_MDI_BULB            "\xF3\xB0\x8C\xB5" // mdi-lightbulb U+F0335
#define LVGL_MDI_PLUG            "\xF3\xB0\x9A\xA5" // mdi-power-plug U+F06A5
#define LVGL_MDI_TOGGLE          "\xF3\xB0\x94\xA1" // mdi-toggle-switch U+F0521
#define LVGL_MDI_THERMOMETER     "\xF3\xB0\x94\x8F" // mdi-thermometer U+F050F
#define LVGL_MDI_HUMIDITY        "\xF3\xB0\x96\x8E" // mdi-water-percent U+F058E
#define LVGL_MDI_BUTTON          "\xF3\xB1\x8A\xA8" // mdi-gesture-tap-button U+F12A8
#define LVGL_MDI_DIMMER          "\xF3\xB0\x9B\xA8" // mdi-lightbulb-on U+F06E8
#define LVGL_MDI_RADIATOR        "\xF3\xB0\x90\xB8" // mdi-radiator U+F0438
#define LVGL_MDI_FAN             "\xF3\xB0\x88\x90" // mdi-fan U+F0210
#define LVGL_MDI_POWER_SYMBOL    "\xF3\xB0\x90\xA5" // mdi-power U+F0425
#define LVGL_MDI_FLAME           "\xF3\xB0\x88\xB8" // mdi-fire U+F0238
#define LVGL_MDI_SNOWFLAKE       "\xF3\xB0\x9C\x97" // mdi-snowflake U+F0717
#define LVGL_MDI_MOTION          "\xF3\xB0\xB6\x91" // mdi-motion-sensor U+F0D91
#define LVGL_MDI_AREA            "\xF3\xB0\x89\x8B" // mdi-folder U+F024B
#define LVGL_MDI_BACK            "\xF3\xB0\x81\x8D" // mdi-arrow-left U+F004D
#define LVGL_MDI_PALETTE         "\xF3\xB0\x8F\x98" // mdi-palette U+F03D8
#define LVGL_MDI_EFFECT          "\xF3\xB0\x99\xB4" // mdi-creation U+F0674
#define LVGL_MDI_RECORD          "\xF3\xB0\x91\x8A" // mdi-record U+F044A
#define LVGL_MDI_PLUS            "\xF3\xB0\x90\x95" // mdi-plus U+F0415
#define LVGL_MDI_MINUS           "\xF3\xB0\x8D\xB4" // mdi-minus U+F0374
#define LVGL_MDI_TOGGLE_OFF      "\xF3\xB0\x94\xA2" // mdi-toggle-switch-off U+F0522
#define LVGL_MDI_BRIGHTNESS      "\xF3\xB0\x83\x9F" // mdi-brightness-6 U+F00DF
#define LVGL_MDI_COLOR_TEMP      "\xF3\xB0\x94\x90" // mdi-thermometer-lines U+F0510
#define LVGL_MDI_CO2             "\xF3\xB0\x9F\xA4" // mdi-molecule-co2 U+F07E4
#define LVGL_MDI_LOCK            "\xF3\xB0\x8C\xBE" // mdi-lock U+F033E
#define LVGL_MDI_GAUGE           "\xF3\xB0\x8A\x9A" // mdi-gauge U+F029A
#define LVGL_MDI_CAMERA          "\xF3\xB0\x84\x80" // mdi-camera U+F0100
#define LVGL_MDI_REMOTE          "\xF3\xB0\x91\x94" // mdi-remote U+F0454
#define LVGL_MDI_LIGHTBULB_OFF   "\xF3\xB0\xB9\x8F" // mdi-lightbulb-off U+F0E4F
#define LVGL_MDI_LIGHTBULB_ON    "\xF3\xB0\x9B\xA8" // mdi-lightbulb-on U+F06E8
#define LVGL_MDI_FLASH_OFF       "\xF3\xB0\x89\x83" // mdi-flash-off U+F0243
#define LVGL_MDI_HOME            "\xF3\xB0\x8B\x9C" // mdi-home U+F02DC
#define LVGL_MDI_HOME_ASSISTANT  "\xF3\xB0\x9F\x90" // mdi-home-assistant U+F07D0
#define LVGL_MDI_WIFI            "\xF3\xB0\x96\xA9" // mdi-wifi U+F05A9
#define LVGL_MDI_WIFI_REMOVE     "\xF3\xB1\x9B\x85" // mdi-wifi-remove U+F16C5
#define LVGL_MDI_WIFI_ALERT      "\xF3\xB1\x9A\xB5" // mdi-wifi-alert U+F16B5
#define LVGL_MDI_WIFI_OFF        "\xF3\xB0\x96\xAA" // mdi-wifi-off U+F05AA
