/**
 * Generated by scripts/build_number.py - do not edit
 *
 * build 15517
 * date  2026-10-05 09:16:44
 */

#include <Arduino_compat.h>
#include "kfc_fw_config.h"

// the complete short firmware version as a single flash string, e.g. "0.0.9 Build 15517"
// the build number below is the suffix of this string and shares its flash location
static const char __firmware_short_version[] PROGMEM = FIRMWARE_VERSION_STR " Build " "15517";

const __FlashStringHelper *KFCFWConfiguration::getShortFirmwareVersion()
{
    return FPSTR(__firmware_short_version);
}

const __FlashStringHelper *KFCFWConfiguration::getBuildNumberString()
{
    return FPSTR(__firmware_short_version + (sizeof(FIRMWARE_VERSION_STR " Build ") - 1));
}

uint32_t KFCFWConfiguration::getBuildNumber()
{
    return 15517;
}

const __FlashStringHelper *KFCFWConfiguration::getFirmwareVersion()
{
    #if ESP32
        return F(FIRMWARE_VERSION_STR " Build " "15517" "-" ARDUINO_ESP32_RELEASE " " __DATE__ " " __TIME__);
    #elif ESP8266
        return F(FIRMWARE_VERSION_STR " Build " "15517" "-" ARDUINO_ESP8266_RELEASE " " __DATE__ " " __TIME__);
    #else
        return F(FIRMWARE_VERSION_STR " Build " "15517" " " __DATE__ " " __TIME__);
    #endif
}
