// AUTO GENERATED FILE - DO NOT MODIFY
#include "spgm_auto_strings.h"
PROGMEM_STRING_DEF(login_failure_file, "/.pvt/login_failures");
PROGMEM_STRING_DEF(mime_application_json, "application/json");
PROGMEM_STRING_DEF(mime_text_html, "text/html");
PROGMEM_STRING_DEF(Address, "Address");
PROGMEM_STRING_DEF(Hostname, "Hostname");
PROGMEM_STRING_DEF(_var_zeroconf, "${zeroconf:");
PROGMEM_STRING_DEF(true, "true");
PROGMEM_STRING_DEF(strftime_date_time_zone, "%FT%T %Z");
PROGMEM_STRING_DEF(Connection, "Connection");
PROGMEM_STRING_DEF(close, "close");
PROGMEM_STRING_DEF(keep_alive, "keep-alive");
PROGMEM_STRING_DEF(Content_Length, "Content-Length");
PROGMEM_STRING_DEF(Cache_Control, "Cache-Control");
PROGMEM_STRING_DEF(Set_Cookie, "Set-Cookie");
PROGMEM_STRING_DEF(Authorization, "Authorization");
PROGMEM_STRING_DEF(Bearer_, "Bearer ");
PROGMEM_STRING_DEF(false, "false");
PROGMEM_STRING_DEF(null, "null");
PROGMEM_STRING_DEF(mqtt, "mqtt");
PROGMEM_STRING_DEF(alarm, "alarm");
PROGMEM_STRING_DEF(on, "on");
PROGMEM_STRING_DEF(off, "off");
PROGMEM_STRING_DEF(yes, "yes");
PROGMEM_STRING_DEF(no, "no");
PROGMEM_STRING_DEF(success, "success");
PROGMEM_STRING_DEF(failure, "failure");
PROGMEM_STRING_DEF(0x_08x, "0x%08x");
PROGMEM_STRING_DEF(AP, "AP");
PROGMEM_STRING_DEF(Accept_Encoding, "Accept-Encoding");
PROGMEM_STRING_DEF(Access_Point, "Access Point");
PROGMEM_STRING_DEF(Action, "Action");
PROGMEM_STRING_DEF(Admin, "Admin");
PROGMEM_STRING_DEF(Alarm, "Alarm");
PROGMEM_STRING_DEF(Animation, "Animation");
PROGMEM_STRING_DEF(Anonymous, "Anonymous");
PROGMEM_STRING_DEF(Authentication, "Authentication");
PROGMEM_STRING_DEF(Auto, "Auto");
PROGMEM_STRING_DEF(Brightness, "Brightness");
PROGMEM_STRING_DEF(Busy, "Busy");
PROGMEM_STRING_DEF(Change_Password, "Change Password");
PROGMEM_STRING_DEF(Channel, "Channel");
PROGMEM_STRING_DEF(Client, "Client");
PROGMEM_STRING_DEF(Closed, "Closed");
PROGMEM_STRING_DEF(Color, "Color");
PROGMEM_STRING_DEF(Configuration, "Configuration");
PROGMEM_STRING_DEF(Content_Encoding, "Content-Encoding");
PROGMEM_STRING_DEF(Cookie, "Cookie");
PROGMEM_STRING_DEF(DHCP, "DHCP");
PROGMEM_STRING_DEF(DHCP_Client, "DHCP Client");
PROGMEM_STRING_DEF(DHCP_Server, "DHCP Server");
PROGMEM_STRING_DEF(DNS_1, "DNS 1");
PROGMEM_STRING_DEF(DNS_2, "DNS 2");
PROGMEM_STRING_DEF(Default, "Default");
PROGMEM_STRING_DEF(Delay, "Delay");
PROGMEM_STRING_DEF(Device, "Device");
PROGMEM_STRING_DEF(Device_Configuration, "Device Configuration");
PROGMEM_STRING_DEF(Device_is_rebooting, "Device is rebooting...\\n");
PROGMEM_STRING_DEF(Disabled, "Disabled");
PROGMEM_STRING_DEF(EN, "EN");
PROGMEM_STRING_DEF(ERROR_, "ERROR:");
PROGMEM_STRING_DEF(Enabled, "Enabled");
PROGMEM_STRING_DEF(Encryption, "Encryption");
PROGMEM_STRING_DEF(Expires, "Expires");
PROGMEM_STRING_DEF(Fading, "Fading");
PROGMEM_STRING_DEF(Flashing, "Flashing");
PROGMEM_STRING_DEF(FormEnumValidator_default_message, "Invalid value: %allowed%");
PROGMEM_STRING_DEF(FormHostValidator_default_message, "Invalid hostname or IP address");
PROGMEM_STRING_DEF(FormLengthValidator_default_message, "This field must be between %min% and %max% characters");
PROGMEM_STRING_DEF(FormRangeValidator_default_message, "This fields value must be between %min% and %max%");
PROGMEM_STRING_DEF(FormRangeValidator_default_message_zero_allowed, "This fields value must be 0 or between %min% and %max%");
PROGMEM_STRING_DEF(FormRangeValidator_invalid_port, "Invalid Port");
PROGMEM_STRING_DEF(FormRangeValidator_invalid_port_range, "Invalid Port (%min%-%max%)");
PROGMEM_STRING_DEF(FormValidator_allowed_macro, "%allowed%");
PROGMEM_STRING_DEF(FormValidator_max_macro, "%max%");
PROGMEM_STRING_DEF(FormValidator_min_macro, "%min%");
PROGMEM_STRING_DEF(Form_value_missing_default_message, "This field is missing");
PROGMEM_STRING_DEF(Gateway, "Gateway");
PROGMEM_STRING_DEF(HIDDEN, "HIDDEN");
PROGMEM_STRING_DEF(HTTP_Server, "HTTP Server");
PROGMEM_STRING_DEF(Home, "Home");
PROGMEM_STRING_DEF(Hz, "Hz");
PROGMEM_STRING_DEF(IP_Address, "IP Address");
PROGMEM_STRING_DEF(Interval, "Interval");
PROGMEM_STRING_DEF(Invalid_brightness, "Invalid brightness");
PROGMEM_STRING_DEF(Invalid_mode, "Invalid mode");
PROGMEM_STRING_DEF(Invalid_port, "Invalid port");
PROGMEM_STRING_DEF(Invalid_time, "Invalid time");
PROGMEM_STRING_DEF(Invalid_username_or_password, "Invalid username or password");
PROGMEM_STRING_DEF(KFCLabs, "KFCLabs");
PROGMEM_STRING_DEF(KFC_Firmware, "KFC Firmware");
PROGMEM_STRING_DEF(Keep_Alive, "Keep Alive");
PROGMEM_STRING_DEF(Last_Modified, "Last-Modified");
PROGMEM_STRING_DEF(Link, "Link");
PROGMEM_STRING_DEF(Location, "Location");
PROGMEM_STRING_DEF(Mode, "Mode");
PROGMEM_STRING_DEF(Move, "Move");
PROGMEM_STRING_DEF(Multiplier, "Multiplier");
PROGMEM_STRING_DEF(NTP_Client, "NTP Client");
PROGMEM_STRING_DEF(NTP_Client_Configuration, "NTP Client Configuration");
PROGMEM_STRING_DEF(NTP_Server___, "NTP Server %u");
PROGMEM_STRING_DEF(Name, "Name");
PROGMEM_STRING_DEF(Network, "Network");
PROGMEM_STRING_DEF(Network_Configuration, "Network Configuration");
PROGMEM_STRING_DEF(No, "No");
PROGMEM_STRING_DEF(None, "None");
PROGMEM_STRING_DEF(Not_supported, "Not supported");
PROGMEM_STRING_DEF(OK, "OK");
PROGMEM_STRING_DEF(Off, "Off");
PROGMEM_STRING_DEF(Offline, "Offline");
PROGMEM_STRING_DEF(On, "On");
PROGMEM_STRING_DEF(Open, "Open");
PROGMEM_STRING_DEF(Passphrase, "Passphrase");
PROGMEM_STRING_DEF(Password, "Password");
PROGMEM_STRING_DEF(Port, "Port");
PROGMEM_STRING_DEF(Pragma, "Pragma");
PROGMEM_STRING_DEF(Protection, "Protection");
PROGMEM_STRING_DEF(RFC7231_date, "%a, %d %b %Y %H:%M:%S GMT");
PROGMEM_STRING_DEF(Rainbow, "Rainbow");
PROGMEM_STRING_DEF(Reboot_Device, "Reboot Device");
PROGMEM_STRING_DEF(Refresh_Interval, "Refresh Interval");
PROGMEM_STRING_DEF(Running, "Running");
PROGMEM_STRING_DEF(SID, "SID");
PROGMEM_STRING_DEF(SPIFFS_tmp_dir, "/.tmp/");
PROGMEM_STRING_DEF(SRV, "SRV");
PROGMEM_STRING_DEF(SSDP_Discovery, "SSDP Discovery");
PROGMEM_STRING_DEF(SSID, "SSID");
PROGMEM_STRING_DEF(STA, "STA");
PROGMEM_STRING_DEF(Save_Changes, "Save Changes");
PROGMEM_STRING_DEF(Serial_Console, "Serial Console");
PROGMEM_STRING_DEF(Server, "Server");
PROGMEM_STRING_DEF(Software_Serial, "Software Serial");
PROGMEM_STRING_DEF(Solid_Color, "Solid Color");
PROGMEM_STRING_DEF(Speed, "Speed");
PROGMEM_STRING_DEF(Station_Mode, "Station Mode");
PROGMEM_STRING_DEF(Status, "Status");
PROGMEM_STRING_DEF(Status_LED_Mode, "Status LED Mode");
PROGMEM_STRING_DEF(Stopped, "Stopped");
PROGMEM_STRING_DEF(Subnet, "Subnet");
PROGMEM_STRING_DEF(Success, "Success");
PROGMEM_STRING_DEF(Timeout, "Timeout");
PROGMEM_STRING_DEF(Timezone, "Timezone");
PROGMEM_STRING_DEF(Title, "Title");
PROGMEM_STRING_DEF(Topic, "Topic");
PROGMEM_STRING_DEF(Turn, "Turn");
PROGMEM_STRING_DEF(Type, "Type");
PROGMEM_STRING_DEF(Username, "Username");
PROGMEM_STRING_DEF(WebUI, "Web UI");
PROGMEM_STRING_DEF(Web_Alerts, "Web Alerts");
PROGMEM_STRING_DEF(WiFi, "WiFi");
PROGMEM_STRING_DEF(WiFi_Configuration, "WiFi Configuration");
PROGMEM_STRING_DEF(WiFi_Mode, "WiFi Mode");
PROGMEM_STRING_DEF(Yes, "Yes");
PROGMEM_STRING_DEF(Your_session_has_expired, "Your session has expired");
PROGMEM_STRING_DEF(Zeroconf_Logging, "Zeroconf Logging");
PROGMEM_STRING_DEF(Zeroconf_Timeout, "Zeroconf Timeout");
PROGMEM_STRING_DEF(_02x, "%02x");
PROGMEM_STRING_DEF(__pure_virtual, "pure virtual call: %s\\n");
PROGMEM_STRING_DEF(__s_, "/%s/");
PROGMEM_STRING_DEF(_brightness_set, "/brightness/set");
PROGMEM_STRING_DEF(_brightness_state, "/brightness/state");
PROGMEM_STRING_DEF(_checked, " checked");
PROGMEM_STRING_DEF(_color_set, "/color/set");
PROGMEM_STRING_DEF(_color_state, "/color/state");
PROGMEM_STRING_DEF(_effect_set, "/effect/set");
PROGMEM_STRING_DEF(_effect_state, "/effect/state");
PROGMEM_STRING_DEF(_hidden, " hidden");
PROGMEM_STRING_DEF(_html, ".html");
PROGMEM_STRING_DEF(_login_html, "/login.html");
PROGMEM_STRING_DEF(_selected, " selected");
PROGMEM_STRING_DEF(_serial_console, "/serial-console");
PROGMEM_STRING_DEF(_set, "/set");
PROGMEM_STRING_DEF(_state, "/state");
PROGMEM_STRING_DEF(_var_gateway, "${gateway}");
PROGMEM_STRING_DEF(_xml, ".xml");
PROGMEM_STRING_DEF(address, "address");
PROGMEM_STRING_DEF(alert, "alert");
PROGMEM_STRING_DEF(ap_mode, "ap_mode");
PROGMEM_STRING_DEF(applying_html, "applying.html");
PROGMEM_STRING_DEF(auth, "auth");
PROGMEM_STRING_DEF(binary, "binary");
PROGMEM_STRING_DEF(boolean, "boolean");
PROGMEM_STRING_DEF(brightness, "brightness");
PROGMEM_STRING_DEF(busy, "busy");
PROGMEM_STRING_DEF(bytes, "bytes");
PROGMEM_STRING_DEF(cfg, "cfg");
PROGMEM_STRING_DEF(channel__u, "channel_%u");
PROGMEM_STRING_DEF(channels, "channels");
PROGMEM_STRING_DEF(client, "client");
PROGMEM_STRING_DEF(comma_, ", ");
PROGMEM_STRING_DEF(config, "config");
PROGMEM_STRING_DEF(cookie, "cookie");
PROGMEM_STRING_DEF(crash_counter_file, "/.pvt/crash_counter");
PROGMEM_STRING_DEF(crash_dump_file, "/.pvt/crash.%03x");
PROGMEM_STRING_DEF(crit, "crit");
PROGMEM_STRING_DEF(critical, "critical");
PROGMEM_STRING_DEF(current, "current");
PROGMEM_STRING_DEF(daemon, "daemon");
PROGMEM_STRING_DEF(day, "day");
PROGMEM_STRING_DEF(days, "days");
PROGMEM_STRING_DEF(debug, "debug");
PROGMEM_STRING_DEF(defaultPassword, "12345678");
PROGMEM_STRING_DEF(default_password_warning, "WARNING! Default password has not been changed");
PROGMEM_STRING_DEF(deflate, "deflate");
PROGMEM_STRING_DEF(description_xml, "description.xml");
PROGMEM_STRING_DEF(dev_hostn, "dev_hostn");
PROGMEM_STRING_DEF(dev_title, "dev_title");
PROGMEM_STRING_DEF(device, "device");
PROGMEM_STRING_DEF(device_html, "device.html");
PROGMEM_STRING_DEF(dir, "dir");
PROGMEM_STRING_DEF(disabled, "disabled");
PROGMEM_STRING_DEF(display, "display");
PROGMEM_STRING_DEF(domain, "domain");
PROGMEM_STRING_DEF(ds3231_id_lost_power, "ds3231_lost_power");
PROGMEM_STRING_DEF(ds3231_id_temp, "ds3231_temp");
PROGMEM_STRING_DEF(ds3231_id_time, "ds3231_time");
PROGMEM_STRING_DEF(emerg, "emerg");
PROGMEM_STRING_DEF(emergency, "emergency");
PROGMEM_STRING_DEF(enabled, "enabled");
PROGMEM_STRING_DEF(encryption, "encryption");
PROGMEM_STRING_DEF(energy, "energy");
PROGMEM_STRING_DEF(energy_total, "energy_total");
PROGMEM_STRING_DEF(err, "err");
PROGMEM_STRING_DEF(error, "error");
PROGMEM_STRING_DEF(factory_html, "factory.html");
PROGMEM_STRING_DEF(file_manager_base_uri, "/file_manager/");
PROGMEM_STRING_DEF(file_manager_html_uri, "file-manager.html");
PROGMEM_STRING_DEF(filename, "filename");
PROGMEM_STRING_DEF(float, "float");
PROGMEM_STRING_DEF(frequency, "frequency");
PROGMEM_STRING_DEF(fs_mapping_dir, "/webui/");
PROGMEM_STRING_DEF(fs_mapping_listings, "/webui/.listings");
PROGMEM_STRING_DEF(get_, "get_");
PROGMEM_STRING_DEF(gzip, "gzip");
PROGMEM_STRING_DEF(hPa, "hPa");
PROGMEM_STRING_DEF(heap, "heap");
PROGMEM_STRING_DEF(hidden, "hidden");
PROGMEM_STRING_DEF(host, "host");
PROGMEM_STRING_DEF(hour, "hour");
PROGMEM_STRING_DEF(htmlentities_acute, "&acute;");
PROGMEM_STRING_DEF(htmlentities_amp, "&amp;");
PROGMEM_STRING_DEF(htmlentities_apos, "&apos;");
PROGMEM_STRING_DEF(htmlentities_copy, "&copy;");
PROGMEM_STRING_DEF(htmlentities_deg, "&deg;");
PROGMEM_STRING_DEF(htmlentities_equals, "&equals;");
PROGMEM_STRING_DEF(htmlentities_gt, "&gt;");
PROGMEM_STRING_DEF(htmlentities_lt, "&lt;");
PROGMEM_STRING_DEF(htmlentities_micro, "&plusmn;");
PROGMEM_STRING_DEF(htmlentities_num, "&num;");
PROGMEM_STRING_DEF(htmlentities_percnt, "&percnt;");
PROGMEM_STRING_DEF(htmlentities_plusmn, "&micro;");
PROGMEM_STRING_DEF(htmlentities_quest, "&quest;");
PROGMEM_STRING_DEF(htmlentities_quot, "&quot;");
PROGMEM_STRING_DEF(http, "http");
PROGMEM_STRING_DEF(httpmode, "httpmode");
PROGMEM_STRING_DEF(https, "https");
PROGMEM_STRING_DEF(humidity, "humidity");
PROGMEM_STRING_DEF(id, "id");
PROGMEM_STRING_DEF(image_type, "image_type");
PROGMEM_STRING_DEF(index_html, "index.html");
PROGMEM_STRING_DEF(info, "info");
PROGMEM_STRING_DEF(int, "int");
PROGMEM_STRING_DEF(interval, "interval");
PROGMEM_STRING_DEF(iot_blinds_control_state_file, "/.pvt/blinds_ctrl.state");
PROGMEM_STRING_DEF(iot_sensor_hlw80xx_state_file, "/.pvt/hlw80xx.state");
PROGMEM_STRING_DEF(iot_switch_states_file, "/.pvt/switch.states");
PROGMEM_STRING_DEF(ip_8_8_8_8, "8.8.8.8");
PROGMEM_STRING_DEF(is_, "is_");
PROGMEM_STRING_DEF(kWh, "kWh");
PROGMEM_STRING_DEF(keep, "keep");
PROGMEM_STRING_DEF(keepalive, "keepalive");
PROGMEM_STRING_DEF(kern, "kern");
PROGMEM_STRING_DEF(kfcfw, "kfcfw");
PROGMEM_STRING_DEF(kfcmdns, "kfcmdns");
PROGMEM_STRING_DEF(lifetime, "lifetime");
PROGMEM_STRING_DEF(light_sensor, "light_sensor");
PROGMEM_STRING_DEF(local0, "local0");
PROGMEM_STRING_DEF(local1, "local1");
PROGMEM_STRING_DEF(local2, "local2");
PROGMEM_STRING_DEF(local3, "local3");
PROGMEM_STRING_DEF(local4, "local4");
PROGMEM_STRING_DEF(local5, "local5");
PROGMEM_STRING_DEF(local6, "local6");
PROGMEM_STRING_DEF(local7, "local7");
PROGMEM_STRING_DEF(lock_channels, "lock_channels");
PROGMEM_STRING_DEF(logger_filename_access, "/.logs/access");
PROGMEM_STRING_DEF(logger_filename_debug, "/.logs/debug");
PROGMEM_STRING_DEF(logger_filename_error, "/.logs/error");
PROGMEM_STRING_DEF(logger_filename_messags, "/.logs/messages");
PROGMEM_STRING_DEF(logger_filename_security, "/.logs/security");
PROGMEM_STRING_DEF(logger_filename_warning, "/.logs/warning");
PROGMEM_STRING_DEF(login_html, "/login.html");
PROGMEM_STRING_DEF(mA, "mA");
PROGMEM_STRING_DEF(mail, "mail");
PROGMEM_STRING_DEF(main, "main");
PROGMEM_STRING_DEF(max, "max");
PROGMEM_STRING_DEF(message, "message");
PROGMEM_STRING_DEF(metrics, "metrics");
PROGMEM_STRING_DEF(milliseconds, "milliseconds");
PROGMEM_STRING_DEF(mime_application_javascript, "application/javascript");
PROGMEM_STRING_DEF(mime_application_pdf, "application/pdf");
PROGMEM_STRING_DEF(mime_application_x_gzip, "application/x-gzip");
PROGMEM_STRING_DEF(mime_application_zip, "application/zip");
PROGMEM_STRING_DEF(mime_font_eot, "font/eot");
PROGMEM_STRING_DEF(mime_font_ttf, "font/ttf");
PROGMEM_STRING_DEF(mime_font_woff, "font/woff");
PROGMEM_STRING_DEF(mime_font_woff2, "font/woff2");
PROGMEM_STRING_DEF(mime_image_bmp, "image/bmp");
PROGMEM_STRING_DEF(mime_image_gif, "image/gif");
PROGMEM_STRING_DEF(mime_image_icon, "image/x-icon");
PROGMEM_STRING_DEF(mime_image_jpeg, "image/jpeg");
PROGMEM_STRING_DEF(mime_image_png, "image/png");
PROGMEM_STRING_DEF(mime_image_svg_xml, "image/svg+xml");
PROGMEM_STRING_DEF(mime_text_css, "text/css");
PROGMEM_STRING_DEF(mime_text_plain, "text/plain");
PROGMEM_STRING_DEF(mime_text_xml, "text/xml");
PROGMEM_STRING_DEF(min, "min");
PROGMEM_STRING_DEF(minutes, "minutes");
PROGMEM_STRING_DEF(mode, "mode");
PROGMEM_STRING_DEF(moon_phase_0, "Full Moon");
PROGMEM_STRING_DEF(moon_phase_1, "Waning Gibbous");
PROGMEM_STRING_DEF(moon_phase_2, "Last Quarter");
PROGMEM_STRING_DEF(moon_phase_3, "Old Crescent");
PROGMEM_STRING_DEF(moon_phase_4, "New Moon");
PROGMEM_STRING_DEF(moon_phase_5, "New Crescent");
PROGMEM_STRING_DEF(moon_phase_6, "First Quarter");
PROGMEM_STRING_DEF(moon_phase_7, "Waxing Gibbous");
PROGMEM_STRING_DEF(mqtt_switch_set, "/switch/set");
PROGMEM_STRING_DEF(mqtt_switch_state, "/switch/state");
PROGMEM_STRING_DEF(ms, "ms");
PROGMEM_STRING_DEF(n_a, "n/a");
PROGMEM_STRING_DEF(name, "name");
PROGMEM_STRING_DEF(network, "network");
PROGMEM_STRING_DEF(network_html, "network.html");
PROGMEM_STRING_DEF(network_settings, "network_settings");
PROGMEM_STRING_DEF(no_cache, "no-cache");
PROGMEM_STRING_DEF(notice, "notice");
PROGMEM_STRING_DEF(npwd, "npwd");
PROGMEM_STRING_DEF(ntp, "ntp");
PROGMEM_STRING_DEF(open, "open");
PROGMEM_STRING_DEF(openweathermap_api_url, "http://api.openweathermap.org/data/2.5/{api_type}?q={query}&appid={api_key}");
PROGMEM_STRING_DEF(password, "password");
PROGMEM_STRING_DEF(password2, "password2");
PROGMEM_STRING_DEF(password_html, "password.html");
PROGMEM_STRING_DEF(performance, "performance");
PROGMEM_STRING_DEF(performance_mode, "performance_mode");
PROGMEM_STRING_DEF(pf, "pf");
PROGMEM_STRING_DEF(ping_monitor, "ping_monitor");
PROGMEM_STRING_DEF(ping_monitor_cancelled, "Ping cancelled");
PROGMEM_STRING_DEF(ping_monitor_end_response, "Total answer from %s sent %d recevied %d time %ld ms");
PROGMEM_STRING_DEF(ping_monitor_ethernet_detected, "Detected eth address %s");
PROGMEM_STRING_DEF(ping_monitor_ping_for_hostname_failed, "Pinging %s failed");
PROGMEM_STRING_DEF(ping_monitor_request_timeout, "Request timed out.");
PROGMEM_STRING_DEF(ping_monitor_response, "%d bytes from %s: icmp_seq=%d ttl=%d time=%ld ms");
PROGMEM_STRING_DEF(ping_monitor_service, "Ping Monitor Service");
PROGMEM_STRING_DEF(ping_monitor_service_status, "Ping monitor service has been %s");
PROGMEM_STRING_DEF(ping_monitor_unknown_service, "ping: %s: Name or service not known");
PROGMEM_STRING_DEF(placeholder, "placeholder");
PROGMEM_STRING_DEF(plugin_name_rd, "rd");
PROGMEM_STRING_DEF(port, "port");
PROGMEM_STRING_DEF(power, "power");
PROGMEM_STRING_DEF(prefix, "prefix");
PROGMEM_STRING_DEF(pressure, "pressure");
PROGMEM_STRING_DEF(private, "private");
PROGMEM_STRING_DEF(public, "public");
PROGMEM_STRING_DEF(pwm, "pwm");
PROGMEM_STRING_DEF(readonly, "readonly");
PROGMEM_STRING_DEF(reboot, "reboot");
PROGMEM_STRING_DEF(reboot_html, "reboot.html");
PROGMEM_STRING_DEF(rebooting_html, "rebooting.html");
PROGMEM_STRING_DEF(refresh, "refresh");
PROGMEM_STRING_DEF(remote_html, "remote.html");
PROGMEM_STRING_DEF(safe_mode, "safe_mode");
PROGMEM_STRING_DEF(safe_mode_enabled, "Device started in SAFE MODE");
PROGMEM_STRING_DEF(sec, "sec");
PROGMEM_STRING_DEF(seconds, "seconds");
PROGMEM_STRING_DEF(secure, "secure");
PROGMEM_STRING_DEF(sensors, "sensors");
PROGMEM_STRING_DEF(serial_console_html, "serial-console.html");
PROGMEM_STRING_DEF(server, "server");
PROGMEM_STRING_DEF(server_crt, "/server.crt");
PROGMEM_STRING_DEF(server_key, "/server.key");
PROGMEM_STRING_DEF(set_, "set_");
PROGMEM_STRING_DEF(set_all, "set_all");
PROGMEM_STRING_DEF(size, "size");
PROGMEM_STRING_DEF(slash, "/");
PROGMEM_STRING_DEF(softap, "softap");
PROGMEM_STRING_DEF(softap_, "softap_");
PROGMEM_STRING_DEF(standby, "standby");
PROGMEM_STRING_DEF(standby_mode, "standby_mode");
PROGMEM_STRING_DEF(started, "started");
PROGMEM_STRING_DEF(state, "state");
PROGMEM_STRING_DEF(states, "states");
PROGMEM_STRING_DEF(station, "station");
PROGMEM_STRING_DEF(station_mode, "station_mode");
PROGMEM_STRING_DEF(status, "status");
PROGMEM_STRING_DEF(status__u, "status=%u");
PROGMEM_STRING_DEF(status_html, "status.html");
// PROGMEM_STRING_DEF(stk500v1_log_file, "/stk500v1/debug.log");
// PROGMEM_STRING_DEF(stk500v1_sig_file, "/stk500v1/atmega.csv");
// PROGMEM_STRING_DEF(stk500v1_tmp_file, "/stk500v1/firmware_tmp.hex");
PROGMEM_STRING_DEF(stopped, "stopped");
PROGMEM_STRING_DEF(string, "string");
PROGMEM_STRING_DEF(sys, "sys");
PROGMEM_STRING_DEF(syslog, "syslog");
PROGMEM_STRING_DEF(tcp, "tcp");
PROGMEM_STRING_DEF(temperature, "temperature");
PROGMEM_STRING_DEF(ticks, "ticks");
PROGMEM_STRING_DEF(timeout, "timeout");
PROGMEM_STRING_DEF(timezone, "timezone");
PROGMEM_STRING_DEF(title, "title");
PROGMEM_STRING_DEF(topic, "topic");
PROGMEM_STRING_DEF(udp, "udp");
PROGMEM_STRING_DEF(update_fw_html, "update-fw.html");
PROGMEM_STRING_DEF(upload, "upload");
PROGMEM_STRING_DEF(upload_file, "upload_file");
PROGMEM_STRING_DEF(uptime, "uptime");
PROGMEM_STRING_DEF(user, "user");
PROGMEM_STRING_DEF(username, "username");
PROGMEM_STRING_DEF(value, "value");
PROGMEM_STRING_DEF(values, "values");
PROGMEM_STRING_DEF(vcc, "vcc");
PROGMEM_STRING_DEF(version, "version");
PROGMEM_STRING_DEF(voltage, "voltage");
PROGMEM_STRING_DEF(warn, "warn");
PROGMEM_STRING_DEF(warning, "warning");
PROGMEM_STRING_DEF(weather_station_webui_id, "ws_tft");
PROGMEM_STRING_DEF(webserver, "webserver");
PROGMEM_STRING_DEF(webui, "webui");
PROGMEM_STRING_DEF(wifi, "wifi");
PROGMEM_STRING_DEF(wifi_html, "wifi.html");
PROGMEM_STRING_DEF(wifi_mode, "wifi_mode");
PROGMEM_STRING_DEF(wifi_settings, "wifi_settings");
PROGMEM_STRING_DEF(www_google_com, "www.google.com");
PROGMEM_STRING_DEF(mqtt_state_file, "/.pvt/mqtt.state");
PROGMEM_STRING_DEF(scheduler_config_file, "/.pvt/.scheduler");
PROGMEM_STRING_DEF(Enable_UDP, "Enable UDP");
PROGMEM_STRING_DEF(Enable_MQTT, "Enable MQTT");
PROGMEM_STRING_DEF(UTF8_rocket, "\xf0\x9f\x9a\x80");
PROGMEM_STRING_DEF(UTF8_degreeCelsius, "\xe2\x84\x83");
PROGMEM_STRING_DEF(UTF8_degreeFahrenheit, "\xe2\x84\x89");
PROGMEM_STRING_DEF(UTF8_degree, "\xc2\xb0");
PROGMEM_STRING_DEF(UTF8_degreeC, "\xc2\xb0" "C");
PROGMEM_STRING_DEF(UTF8_degreeF, "\xc2\xb0" "F");
PROGMEM_STRING_DEF(UTF8_minutes_plusminus5percent, "minutes \xc2\xb1" "5%");
PROGMEM_STRING_DEF(default_format_double, "%.2f");
PROGMEM_STRING_DEF(default_format_integer, "\"%05d\"");
PROGMEM_STRING_DEF(_escaped_apostrophe, "\\'");
PROGMEM_STRING_DEF(_escaped_double_quote, "\\\"");
PROGMEM_STRING_DEF(_escaped_backslash, "\\\\");
PROGMEM_STRING_DEF(_escaped_backspace, "\\b");
PROGMEM_STRING_DEF(_escaped_formfeed, "\\f");
PROGMEM_STRING_DEF(_escaped_newline, "\\n");
PROGMEM_STRING_DEF(_escaped_return, "\\r");
PROGMEM_STRING_DEF(_escaped_htab, "\\t");
PROGMEM_STRING_DEF(_escaped_vtab, "\\v");
PROGMEM_STRING_DEF(iot_clock_save_state_file, "/.pvt/device.state");
